=== sillsdev/CarlaLegacy/PAWS/Data/MasterGrammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!--DTD generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<!ELEMENT and EMPTY>
<!ELEMENT catMapper (#PCDATA)>
<!ATTLIST catMapper
	show IDREF #REQUIRED
>
<!ELEMENT generalizedTemplates (#PCDATA)>
<!ELEMENT masterGrammar (rule | generalizedTemplates | specializedTemplates | catMapper | showWhen)*>
<!ELEMENT or EMPTY>
<!ELEMENT rule (#PCDATA)>
<!ATTLIST rule
	show IDREF #IMPLIED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT specializedTemplates (#PCDATA)>
<!ATTLIST specializedTemplates
	show IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #IMPLIED
	value CDATA #REQUIRED
	negateValue (yes | no) "no"
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
	show IDREF #REQUIRED
>

=== sillsdev/CarlaLegacy/PAWS/XMLGrammarDescriptions/GrammarIP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE masterGrammar SYSTEM "..\Data\MasterGrammar.dtd">
<masterGrammar>
	<rule>
rule {IP option conj - conjoined IPs}
IP = (InitConj) IP_1 Conj IP_2
	&lt;IP head&gt; = &lt;IP_1 head&gt;
	&lt;Conj head type conjoins_IP&gt; = +
	&lt;IP conjoined&gt; = +
	&lt;IP_1 conjoined&gt; = -	|limit recursion
	&lt;IP option&gt; = conj
</rule>
	<rule show="IPoption1a">
rule {IP option 1a - no subject for imperatives}
IP = I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;I' head infl mood imperative&gt; = +
	&lt;IP head type question&gt; = -
	&lt;IP option&gt; = 1a
</rule>
	<showWhen id="IPoption1a">
		<whenValue element="ip" attr="proDrop" value="no" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="VSO" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="OSV" negateValue="yes"/>
	</showWhen>
	<rule show="IPoption1b">
rule {IP option 1b - subject pro-drop, not passive}
IP = I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = +
	&lt;IP head infl mood imperative&gt; = -
		{&lt;I' head type transitive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = +
	&lt;I' head subject head agr&gt; = &lt;I' head object head agr&gt;
	}
	&lt;IP head type passive&gt; = -
	{&lt;IP head type question&gt; = -
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = AdvP
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = PP
	}
	&lt;IP head&gt; == [type:[reciprocal:+]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;IP head&gt; == [object:[head:[type:[reciprocal:+]]]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;IP option&gt; = 1b
</rule>
	<showWhen id="IPoption1b">
		<whenValue element="ip" attr="proDrop" value="yes" negateValue="no"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="VSO" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="OSV" negateValue="yes"/>
		<or/>
		<whenValue element="ip" attr="proDrop" value="yesClitic" negateValue="no"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="VSO" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="OSV" negateValue="yes"/>
	</showWhen>
	<rule show="IPoption1c">
rule {IP option 1c - subject pro-drop, passive}
IP = I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = +
	&lt;IP head infl mood imperative&gt; = -
	&lt;IP head type passive&gt; = +
	{&lt;IP head type question&gt; = -
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = AdvP
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = PP
	}
	&lt;IP option&gt; = 1c
</rule>
	<showWhen id="IPoption1c">
		<whenValue element="ip" attr="proDrop" value="yes" negateValue="no"/>
		<and/>
		<whenValue element="ip" attr="passive" value="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="VSO" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="OSV" negateValue="yes"/>
		<or/>
		<whenValue element="ip" attr="proDrop" value="yesClitic" negateValue="no"/>
		<and/>
		<whenValue element="ip" attr="passive" value="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="VSO" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="OSV" negateValue="yes"/>
	</showWhen>
	<rule show="IPoption2a">
rule {IP option 2a - subject initial, required, not passive}
IP = DP I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = -
	&lt;I' head subject&gt; = &lt;DP&gt;
		{&lt;I' head type transitive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = +
	&lt;DP head agr&gt; = &lt;I' head object head agr&gt;
	}
	&lt;DP head type wh&gt; = -
	&lt;IP head type passive&gt; = -
	&lt;DP head type possessive&gt; = -  		|subject not possessive
	&lt;DP head type reflexive&gt; = -		|subject not reflexive
	&lt;DP head type reciprocal&gt; = -		|subject not reciprocal
	&lt;DP head type suffix poss&gt; = -         | only in possessor position
	&lt;DP head type prefix poss&gt; = -
	&lt;DP head type prefix copular&gt; = -      | only in no V/Aux copulars
	&lt;DP head type suffix copular&gt; = -
	&lt;IP head type prefix&gt; &lt;= &lt;DP head type prefix&gt;
	&lt;I' head type negative&gt; &lt;= &lt;DP head type negative&gt;    <!-- |polarity from DP -->
	&lt;IP head&gt; == [type:[reciprocal:+]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;IP head&gt; == [object:[head:[type:[reciprocal:+]]]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;DP head&gt; == ~[case:accusative]
	&lt;IP option&gt; = 2a
</rule>
	<showWhen id="IPoption2a">
		<whenValue element="typology" attr="wordOrder" value="SVO" negateValue="no"/>
		<and/>
		<whenValue element="neg" attr="subjVerbRequired" value="yes" negateValue="yes"/>
		<or/>
		<whenValue element="typology" attr="wordOrder" value="SOV" negateValue="no"/>
		<and/>
		<whenValue element="neg" attr="subjVerbRequired" value="yes" negateValue="yes"/>
	</showWhen>
	<rule show="IPoption2aNegVerb">
rule {IP option 2aNegVerb - subject initial, not passive, neg subj requires neg verb}
IP = DP I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = -
	&lt;I' head subject&gt; = &lt;DP&gt;
		{&lt;I' head type transitive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = -
		/&lt;I' head type transitive&gt; = +
	&lt;I' head object head type reflexive&gt; = +
	&lt;DP head agr&gt; = &lt;I' head object head agr&gt;
	}
	&lt;DP head type wh&gt; = -
	&lt;IP head type passive&gt; = -
	&lt;DP head type possessive&gt; = -  		|subject not possessive
	&lt;DP head type reflexive&gt; = -		|subject not reflexive
	&lt;DP head type reciprocal&gt; = -		|subject not reciprocal
	&lt;DP head type suffix poss&gt; = -         | only in possessor position
	&lt;DP head type prefix poss&gt; = -
	&lt;DP head type prefix copular&gt; = -      | only in no V/Aux copulars
	&lt;DP head type suffix copular&gt; = -
	&lt;IP head type prefix&gt; &lt;= &lt;DP head type prefix&gt;
	&lt;IP head&gt; == [type:[reciprocal:+]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;IP head&gt; == [object:[head:[type:[reciprocal:+]]]] -&gt;
					 [subject:[head:[agr:[number:plural]]]]
	&lt;DP head&gt; == ~[case:accusative]
	&lt;I' head&gt; == [subject:[head:[type:[negative:+]]]] -&gt;  | if subject negative, verb must be
					 [type:[negative:+]]
	&lt;IP option&gt; = 2aNegVerb
</rule>
	<showWhen id="IPoption2aNegVerb">
		<whenValue element="neg" attr="subjVerbRequired" value="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="SVO" negateValue="no"/>
		<or/>
		<whenValue element="neg" attr="subjVerbRequired" value="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="SOV" negateValue="no"/>
	</showWhen>
	<rule show="IPoption2b">
rule {IP option 2b - subject initial, required, passive}
IP = DP I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = -
	&lt;I' head object&gt; = &lt;DP&gt;
	&lt;DP head type wh&gt; = -
	&lt;IP head type passive&gt; = +
	&lt;DP head type possessive&gt; = -  		|subject not possessive
	&lt;DP head type reflexive&gt; = -		|subject not reflexive
	&lt;DP head type reciprocal&gt; = -		|subject not reciprocal
	&lt;DP head type suffix poss&gt; = -         | only in possessor position
	&lt;DP head type prefix poss&gt; = -
	&lt;DP head type prefix copular&gt; = -      | only in no V/Aux copulars
	&lt;DP head type suffix copular&gt; = -
	{&lt;IP head type question&gt; = -
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = AdvP
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = PP
	}
	&lt;IP head type prefix&gt; &lt;= &lt;DP head type prefix&gt;
	&lt;I' head type negative&gt; &lt;= &lt;DP head type negative&gt;    <!-- |polarity from DP -->
	&lt;DP head&gt; == ~[case:accusative]
	&lt;IP option&gt; = 2b
</rule>
	<showWhen id="IPoption2b">
		<whenValue element="neg" attr="subjVerbRequired" value="yes" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="SVO" negateValue="no"/>
		<and/>
		<whenValue element="ip" attr="passive" value="yes"/>
		<or/>
		<whenValue element="neg" attr="subjVerbRequired" value="yes" negateValue="yes"/>
		<and/>
		<whenValue element="typology" attr="wordOrder" value="SOV" negateValue="no"/>
		<and/>
		<whenValue element="ip" attr="passive" value="yes"/>
	</showWhen>
	<rule show="IPoption2bNegVerb">
rule {IP option 2bNegVerb - subject initial, required, passive, neg subj requires neg verb}
IP = DP I'
	&lt;IP head&gt; = &lt;I' head&gt;
	&lt;IP head type pro-drop&gt; = -
	&lt;I' head object&gt; = &lt;DP&gt;
	&lt;DP head type wh&gt; = -
	&lt;IP head type passive&gt; = +
	&lt;DP head type possessive&gt; = -  		|subject not possessive
	&lt;DP head type reflexive&gt; = -		|subject not reflexive
	&lt;DP head type reciprocal&gt; = -		|subject not reciprocal
	&lt;DP head type suffix poss&gt; = -         | only in possessor position
	&lt;DP head type prefix poss&gt; = -
	&lt;DP head type prefix copular&gt; = -      | only in no V/Aux copulars
	&lt;DP head type suffix copular&gt; = -
	{&lt;IP head type question&gt; = -
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = AdvP
	/&lt;IP head type question&gt; = +
	 &lt;IP head fronted cat&gt; = PP
	}
	&lt;IP head type prefix&gt; &lt;= &lt;DP head type prefix&gt;
	&lt;DP head&gt; == ~[case:accusative]
	&lt;I' head&gt; == [subject:[head:[type:[negative:+]]]] -&gt;  | if subject negative, verb must be
					 [type:[negative:+]]
	&lt;IP option&gt; = 2bNegVerb
</rule>
	<showWhen id="IPoption2bNegVerb">
		<whenValue element="neg" attr="subjVerbRequired" value="yes"/>
