=== sillsdev/CarlaLegacy/PAWS/Data/PAWSSKWriterDescription.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit Writer Page Description  -->
<!-- Entity definitions -->
<!ENTITY % chunk "p | example | table | ol | ul | dl">
<!ENTITY % embedded "case | text | langData | langName | gloss | exampleRef | sectionRef | comment | object | br | category | feature">
<!ENTITY nbsp "&#160;">
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT caption (content | %embedded;)*>
<!-- content -->
<!ELEMENT case (caseText*)>
<!ATTLIST case
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
>
<!ELEMENT caseText (#PCDATA)>
<!ATTLIST caseText
	value CDATA #REQUIRED
>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT col (content | %embedded;)*>
<!-- content -->
<!ATTLIST col
	class CDATA #IMPLIED
	show IDREF #IMPLIED
	exampleLoc CDATA #IMPLIED
>
<!-- comments are for the author.  The intent is that they will not show up in
	 the formatted version of the paper. -->
<!ELEMENT comment (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!-- definition description -->
<!ELEMENT dd (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dd
	show IDREF #IMPLIED
>
<!-- definition list -->
<!ELEMENT dl (dt | dd)*>
<!ATTLIST dl
	show IDREF #IMPLIED
>
<!-- definition term -->
<!ELEMENT dt (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dt
	show IDREF #IMPLIED
>
<!ELEMENT example (interlinear | table)>
<!ATTLIST example
	num ID #IMPLIED
	show IDREF #IMPLIED
>
<!-- references to example numbers or example number/letter.
	 Use just num for the example number.
	 Use just letter for an example number/letter combination.
	 One may include parentheses around the date ("both", the default), or
	   one may have no parentheses or just initial or just final.
	 One may append some punctuation (punct) to the end of the number.
	 One may only include the letter (and not the number). -->
<!ELEMENT exampleRef EMPTY>
<!ATTLIST exampleRef
	num CDATA #IMPLIED
	letter CDATA #IMPLIED
	equal (no | yes) "no"
	punct CDATA #IMPLIED
	paren (none | both | initial | final) #IMPLIED
	letterOnly (no | yes) "no"
>
<!ELEMENT feature (#PCDATA)>
<!-- gloss is a way to tag some text as being a gloss in a particular language. -->
<!ELEMENT gloss (content | %embedded;)*>
<!-- content -->
<!ATTLIST gloss
	lang IDREF #REQUIRED
>
<!ELEMENT headerCol (#PCDATA)>
<!ATTLIST headerCol
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT headerRow (headerCol+)>
<!ATTLIST headerRow
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT interlinear EMPTY>
<!ATTLIST interlinear
	exampleLoc CDATA #REQUIRED
>
<!-- langData is a way to tag some text as belonging to a particular language. -->
<!ELEMENT langData (#PCDATA)>
<!-- content -->
<!ELEMENT langName EMPTY>
<!-- object is a generic way to tag a special kind of object.  One can
	 use the CSS stylesheet to format these objects by referring to the
	 class attribute.  -->
<!-- list element -->
<!ELEMENT li (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT object (content | %embedded;)*>
<!-- content -->
<!ATTLIST object
	class CDATA #REQUIRED
>
<!-- ordered list -->
<!ELEMENT ol (li | ol | ul)*>
<!ATTLIST ol
	show IDREF #IMPLIED
>
<!ELEMENT or EMPTY>
<!ELEMENT p (content | %embedded;)*>
<!-- content -->
<!ATTLIST p
	style CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT portion ((section1 | section2 | section3 | section4 | section5 | section6)*, showWhen*)>
<!ELEMENT row (col+)>
<!ATTLIST row
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT secTitle (#PCDATA)>
<!ELEMENT section1 (secTitle, (%chunk; | section2)*)>
<!ATTLIST section1
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section2 (secTitle, (%chunk; | section3)*)>
<!ATTLIST section2
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section3 (secTitle, (%chunk; | section4)*)>
<!ATTLIST section3
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section4 (secTitle, (%chunk; | section5)*)>
<!ATTLIST section4
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section5 (secTitle, (%chunk; | section6)*)>
<!ATTLIST section5
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section6 (secTitle, (%chunk;)*)>
<!ATTLIST section6
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!-- references to sections, etc. -->
<!ELEMENT sectionRef EMPTY>
<!ATTLIST sectionRef
	sec CDATA #REQUIRED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT table (caption?, headerRow?, row+)>
<!ATTLIST table
	border CDATA #IMPLIED
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT text (content | %embedded;)*>
<!ATTLIST text
	show IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #IMPLIED
	value CDATA #REQUIRED
	negateValue (yes | no) "no"
>
<!-- unordered list -->
<!ELEMENT ul (li | ol | ul)*>
<!ATTLIST ul
	show IDREF #IMPLIED
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
	show IDREF #REQUIRED
>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XMLWriterPracticalDescriptions/WriterPracticalProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sProp">
        <secTitle>Proper Names</secTitle>
        <p>
            <content>Proper names are a special kind of noun or phrase that acts syntactically just like other nouns or nominal phrases.  In English, some proper names can stand alone, like </content>
            <langData>Sue</langData>
            <content> and </content>
            <langData>Russia</langData>
            <content>.  Others are like compound nouns, such as </content>
            <langData>George Washington</langData>
            <content>.  Proper names may also contain articles and/or </content>
            <case element="pp" attr="pPos">
                <caseText value="before">prepositional</caseText>
                <caseText value="after">postpositional</caseText>
                <caseText value="both">prepositional and/or postpositional</caseText>
                <caseText value="unknown">prepositional and/or postpositional</caseText>
            </case>
            <content> phrases, as in </content>
			<langData>the United States of America</langData>
			<content>.  Many languages require an article before a name.  Appositives also occur, possibly including a possessor, as in </content>
			<langData>my son, David</langData>
		   <content>, but these will be handled later in section </content><sectionRef sec="sCoordAppositive"/><content>.  In addition, proper names can be modified by adjectives and relative clauses, as in </content>
			<langData>the good, old USA</langData>
			<content> or </content>
			<langData>the Susan Welch that I know</langData>
            <content>.</content>
        </p>
        <p>
            <content>Examples with simple and compound proper names, or those including articles, demonstratives, adjectives, and/or possessors in </content>
            <langName/>
            <content> include:</content>
        </p>
		<example>
			<interlinear exampleLoc="prop/example"/>
		</example>
	   <p show="swClassifiersYesPropYes"><content>In </content><langName/><content>, proper names carry classifiers just like nouns as part of the concord agreement system.</content></p>
	   <p show="swClassifiersYesPropNo"><content>In </content><langName/><content>, proper names do not carry classifiers as nouns do as part of the concord agreement system.</content></p>
	   <p show="swNPArtAndDemNotNo"><content>Proper names in </content><langName/><case element="prop" attr="pnDeterminer">
		  <caseText value="no"> may but are not required to</caseText>
		  <caseText value="yes"> must</caseText>
	   </case><content> contain an </content><case element="np" attr="artAndDem">
		  <caseText value="article">article</caseText>
		  <caseText value="demonstrative">demonstrative</caseText>
		  <caseText value="both">article and/or demonstrative</caseText></case><content> or a possessor.</content></p>
	   <p>
			<content>Examples of proper names with </content>
			<case element="pp" attr="pPos">
				<caseText value="before">prepositional</caseText>
                <caseText value="after">postpositional</caseText>
                <caseText value="both">prepositional and/or postpositional</caseText>
                <caseText value="unknown">prepositional and/or postpositional</caseText>
            </case>
            <content> phrases in </content>
            <langName/>
            <content> include:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/ppExample"/>
        </example>
        <p>
            <content>Examples of proper names modified by relative clauses included in simple full sentences in </content>
            <langName/>
            <content> include:</content>
        </p>
        <example>
			<interlinear exampleLoc="prop/relClExample"/>
		</example>
	</section1>
   <showWhen id="swClassifiersYesPropYes">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="yes"/>
   </showWhen>
   <showWhen id="swClassifiersYesPropNo">
	  <whenValue element="typology"  attr="classifier" value="yesAgr"/>
	  <and/>
	  <whenValue element="prop" attr="pnClassifier" value="no"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
	  <whenValue element="np" attr="artAndDem" value="no" negateValue="yes"/>
   </showWhen>
</portion>

=== sillsdev/CarlaLegacy/PAWS/XMLWriterDescriptions/WriterRelCl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
	<section1 id="sRelCl">
		<secTitle>Relative Clauses</secTitle>
		<p>
			<content>Relative clauses normally modify a head noun and have one of four structures:</content>
		</p>
		<ul>
			<li>
				<content>like a complement clause headed by 'that', as in </content>
				<langData>the man that came to the meeting late</langData>
				<content>;</content>
			</li>
			<li>
				<content>like a content question with 'who' or 'which' fronted, as in </content>
				<langData>the man who came to the meeting late</langData>
				<content>;</content>
			</li>
			<li>
				<content>(or for some languages other than English) like a complement clause but with a special relative marker occurring in the complementizer position, or possibly with two markers which occur on each sides of the relative clause;</content>
			</li>
			<li>
				<content>(or for some languages other than English) like a regular sentence with a relative marker attached to the verb.</content>
			</li>
		</ul>
		<p>
			<content>Some languages also allow one of the above structures to occur by itself as a nominal phrase without a head noun to modify, usually called "headless" relative clauses.</content>
		</p>
		<p>
			<content>&#x20;</content>
			<langName/>
			<content>&#x20;</content>
			<case element="relcl" attr="type">
				<caseText value="none"> does not have any kind of relative clause.</caseText>
				<caseText value="IP"> has relative clauses which are like a regular sentence with a relative marker attached to the verb.</caseText>
				<caseText value="CP"> has relative clauses </caseText>
			</case>
			<content>&#x20;</content>
			<text show="swRelClTypeCP">
				<content>&#x20;</content>
				<case element="relcl" attr="compCP">
					<caseText value="no">which are like questions because a "wh" word is fronted.</caseText>
					<caseText value="yes">which are like complement clauses with relative markers that </caseText>
					<caseText value="yesBoth">which are like questions because a "wh" word is fronted and also relative clauses which are like complement clauses with relative markers that </caseText>
				</case>
				<text show="swRelClCompCPNotNo">
					<content>are </content>
					<case element="relcl" attr="relWord">
						<caseText value="yes">written as a separate word.</caseText>
						<caseText value="no">clitics which attach to another word at the edge of the relative clause.</caseText>
					</case>
					<content>&#x20;</content>
					<text show="swRelClTypeCPCompClitic">
						<content>&#x20;</content>
						<case element="relcl" attr="relCliticPos">
							<caseText value="before">These clitics are pro-clitics.</caseText>
							<caseText value="after">These clitics are post-clitics.</caseText>
							<caseText value="both">Some of the clitics are pro-clitics and some are post-clitics.</caseText>
						</case>
						<content>&#x20;</content>
					</text>
					<content>&#x20;</content>
					<text show="swRelClTypeCPCompWord">
						<content>&#x20;</content>
						<case element="relcl" attr="relCompSame">
							<caseText value="yes">Some of</caseText>
							<caseText value="no">None of</caseText>
						</case>
						<content> the relative markers are the same as the complementizer(s) used in verbal complement clauses.  The relative marker occurs </content>
						<case element="relcl" attr="relCompPos">
							<caseText value="before">before</caseText>
							<caseText value="after">after</caseText>
							<caseText value="either">on either side (but not both sides) of</caseText>
							<caseText value="beforeOrBoth">before or on both sides of</caseText>
							<caseText value="afterOrBoth">after or on both sides of</caseText>
							<caseText value="both">on both sides of</caseText>
						</case>
						<content> the sentence part of the relative clause.</content>
						<text show="swRelClTypeCPCompEitherUnrestricted">
							<content>All of the relative markers can occur on either side.</content>
						</text>
						<content>&#x20;</content>
						<text show="swRelClTypeCPCompEitherRestricted">
							<content>There are restrictions as to which of the relative markers can occur on each side.</content>
						</text>
						<content>&#x20;</content>
					</text>
					<content>&#x20;</content>
				</text>
				<content>&#x20;</content>
			</text>
			<content>&#x20;</content>
			<text show="swRelClTypeCPWh">
				<content>In the "wh"-relative clauses, </content>
				<case element="relcl" attr="whAndComp">
					<caseText value="no">only the "wh"-word occurs without any type of relative marker.</caseText>
					<caseText value="yes">the "wh"-word and the relative marker(s) are required to both be present.</caseText>
					<caseText value="optional">a relative marker may optionally co-occur along with the "wh"-word.</caseText>
				</case>
				<content>&#x20;</content>
			</text>
			<content>&#x20;</content>
		</p>
		<p show="swRelClTypeNotNone">
			<content>Examples of relative clauses in </content>
			<langName/>
			<content> include:</content>
		</p>
		<example show="swRelClTypeNotNone">
			<interlinear exampleLoc="relcl/example"/>
		</example>
		<p show="swRelClTypeNotNone">
			<content>Full sentence examples of the above relative clauses include:</content>
		</p>
		<example show="swRelClTypeNotNone">
			<interlinear exampleLoc="relcl/sentExample"/>
		</example>
		<p show="swRelClTypeNotNone">
			<content>&#x20;</content>
			<langName/>
			<content>&#x20;</content>
			<case element="relcl" attr="headless">
				<caseText value="no">requires a head noun to be present in all relative clauses, so no headless relative clauses are allowed.</caseText>
				<caseText value="yes">allows a head noun to be missing in relative clauses, so headless relative clauses are allowed.</caseText>
			</case>
			<content>&#x20;</content>
		</p>
		<p show="swRelClHeadlessYes">
			<content>Examples of headless relative clauses included in full sentences include:</content>
		</p>
		<example show="swRelClHeadlessYes">
			<interlinear exampleLoc="relcl/headlessExample"/>
		</example>
	</section1>
	<showWhen id="swRelClTypeCP">
		<whenValue element="relcl" attr="type" value="CP"/>
	</showWhen>
<showWhen id="swRelClTypeNotNone">
	<whenValue element="relcl" attr="type" value="none" negateValue="yes"></whenValue>
</showWhen>
	<showWhen id="swRelClTypeCPCompClitic">
		<whenValue element="relcl" attr="relWord" value="no"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no" negateValue="yes"/>
		<or/>
		<whenValue element="relcl" attr="relWord" value="no"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no"/>
		<and/>
		<whenValue element="relcl" attr="whAndComp" value="no" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClCompCPNotNo">
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no" negateValue="yes"/>
		<or/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no"/>
		<and/>
		<whenValue element="relcl" attr="whAndComp" value="no" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClTypeCPCompWord">
		<whenValue element="relcl" attr="relWord" value="yes"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no" negateValue="yes"/>
		<or/>
		<whenValue element="relcl" attr="relWord" value="yes"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no"/>
		<and/>
		<whenValue element="relcl" attr="whAndComp" value="no" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClTypeCPWh">
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="yes" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClTypeCPCompEitherRestricted">
		<whenValue element="relcl" attr="relWord" value="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompEitherRestricted" value="restricted"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no" negateValue="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompPos" value="before" negateValue="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompPos" value="after" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClTypeCPCompEitherUnrestricted">
		<whenValue element="relcl" attr="relWord" value="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompEitherRestricted" value="unrestricted"/>
		<and/>
		<whenValue element="relcl" attr="type" value="CP"/>
		<and/>
		<whenValue element="relcl" attr="compCP" value="no" negateValue="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompPos" value="before" negateValue="yes"/>
		<and/>
		<whenValue element="relcl" attr="relCompPos" value="after" negateValue="yes"/>
	</showWhen>
	<showWhen id="swRelClHeadlessYes">
		<whenValue element="relcl" attr="headless" value="yes"/>
	</showWhen>
</portion>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XMLWriterPracticalSpanishDescriptions/WriterSpPracticalProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
    <section1 id="sProp">
        <secTitle>Los nombres propios</secTitle>
       <p contentType="ctPracticalIntro">
          <content>Los nombres propios son una clase especial de sustantivos o frases que sintácticamente funcionan igual que otros sustantivos o frases nominales.</content>
          </p>
          <p contentType="ctComparativeIntro">
            <content>Los nombres propios son una clase especial de sustantivos o frases que sintácticamente funcionan igual que otros sustantivos o frases nominales. En español, algunos nombres propios pueden presentarse solos, como </content>
            <langData>Susana</langData>
            <content> y </content>
            <langData>Oaxaca</langData>
            <content>.  Otros funcionan como sustantivos compuestos, como </content>
            <langData>George Washington</langData>
             <content>.  Los nombres propios también pueden contener los artículos y/o frases </content>
            <case element="pp" attr="pPos">
                <caseText value="before">preposicionales</caseText>
                <caseText value="after">posposicionales</caseText>
                <caseText value="both">adposicionales</caseText>
                <caseText value="unknown">adposicionales</caseText>
            </case>
            <content>, como en </content>
            <langData>los Estados Unidos de América</langData>
            <content>.  Muchas lenguas requieren un artículo antes de un nombre. También se presentan los apositivos.  En algunos casos aparecen con un posesivo, como en </content>
            <langData>mi hijo, David</langData>
             <content>, pero apositivos se tratann más adelante en la sección </content><sectionRef sec="sCoordAppositive"/><content>.  Además, los nombres propios se pueden modificar con los adjetivos y cláusulas relativas, como en </content>
            <langData>México fuerte y orgulloso</langData>
            <content> o </content>
            <langData>la Susana que conozco</langData>
            <content>.</content>
        </p>
        <p>
            <content>Algunos ejemplos de nombres propios simples y compuestos, o los que se presentan con artículos, demostrativeo, adjetivos o posesivos en el </content>
            <langName/>
            <content> son los siguientes:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/example"/>
        </example>
       <p show="swClassifiersYesPropYes"><content>En el </content><langName/><content>, los nombres propios se marcan con clasificadores lo mismo que sustantivos como parte del sistema de concordancia.</content></p> 
       <p show="swClassifiersYesPropNo"><content>En el </content><langName/><content>, los nombres propios no se marcan con clasificadores al contrario que sustantivos.</content></p>       
       <p show="swNPArtAndDemNotNo"><content>Los nombres propios</content><case element="prop" attr="pnDeterminer">
          <caseText value="no"> pueden</caseText>
          <caseText value="yes"> deben</caseText>
       </case><content> contener un </content><case element="np" attr="artAndDem">
          <caseText value="article">artículo</caseText>
          <caseText value="demonstrative">demostrativo</caseText>
          <caseText value="both">artículo o demostrativo</caseText></case><content> o un posesivo.</content></p>
       <p>
            <content>Algunos ejemplos de nombres propios con frases </content>
            <case element="pp" attr="pPos">
                <caseText value="before">preposicionales</caseText>
                <caseText value="after">posposicionales</caseText>
                <caseText value="both">adposicionales</caseText>
                <caseText value="unknown">adposicionales</caseText>
            </case>
            <content> son los siguientes:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/ppExample"/>
        </example>
        <p>
            <content>Algunos ejemplos de nombres propios modificados por cláusulas relativas en oraciones completas son:</content>
        </p>
        <example>
            <interlinear exampleLoc="prop/relClExample"/>
        </example>
    </section1>
   <showWhen id="swClassifiersYesPropYes">
      <whenValue element="typology"  attr="classifier" value="yesAgr"/>
      <and/>
      <whenValue element="prop" attr="pnClassifier" value="yes"/>
   </showWhen>
   <showWhen id="swClassifiersYesPropNo">
      <whenValue element="typology"  attr="classifier" value="yesAgr"/>
      <and/>
      <whenValue element="prop" attr="pnClassifier" value="no"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
      <whenValue element="np" attr="artAndDem" value="no" negateValue="yes"/>
   </showWhen>
</portion>
