=== sillsdev/CarlaLegacy/PAWS/Data/PAWSSKWriterDescription.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit Writer Page Description  -->
<!-- Entity definitions -->
<!ENTITY % chunk "p | example | table | ol | ul | dl">
<!ENTITY % embedded "case | text | langData | langName | gloss | exampleRef | sectionRef | comment | object | br | category | feature">
<!ENTITY nbsp "&#160;">
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT caption (content | %embedded;)*>
<!-- content -->
<!ELEMENT case (caseText*)>
<!ATTLIST case
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
>
<!ELEMENT caseText (#PCDATA)>
<!ATTLIST caseText
	value CDATA #REQUIRED
>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT col (content | %embedded;)*>
<!-- content -->
<!ATTLIST col
	class CDATA #IMPLIED
	show IDREF #IMPLIED
	exampleLoc CDATA #IMPLIED
>
<!-- comments are for the author.  The intent is that they will not show up in
	 the formatted version of the paper. -->
<!ELEMENT comment (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!-- definition description -->
<!ELEMENT dd (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dd
	show IDREF #IMPLIED
>
<!-- definition list -->
<!ELEMENT dl (dt | dd)*>
<!ATTLIST dl
	show IDREF #IMPLIED
>
<!-- definition term -->
<!ELEMENT dt (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST dt
	show IDREF #IMPLIED
>
<!ELEMENT example (interlinear | table)>
<!ATTLIST example
	num ID #IMPLIED
	show IDREF #IMPLIED
>
<!-- references to example numbers or example number/letter.
	 Use just num for the example number.
	 Use just letter for an example number/letter combination.
	 One may include parentheses around the date ("both", the default), or
	   one may have no parentheses or just initial or just final.
	 One may append some punctuation (punct) to the end of the number.
	 One may only include the letter (and not the number). -->
<!ELEMENT exampleRef EMPTY>
<!ATTLIST exampleRef
	num CDATA #IMPLIED
	letter CDATA #IMPLIED
	equal (no | yes) "no"
	punct CDATA #IMPLIED
	paren (none | both | initial | final) #IMPLIED
	letterOnly (no | yes) "no"
>
<!ELEMENT feature (#PCDATA)>
<!-- gloss is a way to tag some text as being a gloss in a particular language. -->
<!ELEMENT gloss (content | %embedded;)*>
<!-- content -->
<!ATTLIST gloss
	lang IDREF #REQUIRED
>
<!ELEMENT headerCol (#PCDATA)>
<!ATTLIST headerCol
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT headerRow (headerCol+)>
<!ATTLIST headerRow
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT interlinear EMPTY>
<!ATTLIST interlinear
	exampleLoc CDATA #REQUIRED
>
<!-- langData is a way to tag some text as belonging to a particular language. -->
<!ELEMENT langData (#PCDATA)>
<!-- content -->
<!ELEMENT langName EMPTY>
<!-- object is a generic way to tag a special kind of object.  One can
	 use the CSS stylesheet to format these objects by referring to the
	 class attribute.  -->
<!-- list element -->
<!ELEMENT li (content | %embedded; | %chunk;)*>
<!-- content -->
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT object (content | %embedded;)*>
<!-- content -->
<!ATTLIST object
	class CDATA #REQUIRED
>
<!-- ordered list -->
<!ELEMENT ol (li | ol | ul)*>
<!ATTLIST ol
	show IDREF #IMPLIED
>
<!ELEMENT or EMPTY>
<!ELEMENT p (content | %embedded;)*>
<!-- content -->
<!ATTLIST p
	style CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT portion ((section1 | section2 | section3 | section4 | section5 | section6)*, showWhen*)>
<!ELEMENT row (col+)>
<!ATTLIST row
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT secTitle (#PCDATA)>
<!ELEMENT section1 (secTitle, (%chunk; | section2)*)>
<!ATTLIST section1
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section2 (secTitle, (%chunk; | section3)*)>
<!ATTLIST section2
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section3 (secTitle, (%chunk; | section4)*)>
<!ATTLIST section3
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section4 (secTitle, (%chunk; | section5)*)>
<!ATTLIST section4
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section5 (secTitle, (%chunk; | section6)*)>
<!ATTLIST section5
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!ELEMENT section6 (secTitle, (%chunk;)*)>
<!ATTLIST section6
	id ID #REQUIRED
	show IDREF #IMPLIED
>
<!-- references to sections, etc. -->
<!ELEMENT sectionRef EMPTY>
<!ATTLIST sectionRef
	sec CDATA #REQUIRED
>
<!ELEMENT showWhen ((whenValue | useShowWhen), ((or | and), (whenValue | useShowWhen))*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT table (caption?, headerRow?, row+)>
<!ATTLIST table
	border CDATA #IMPLIED
	class CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT text (content | %embedded;)*>
<!ATTLIST text
	show IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #IMPLIED
	value CDATA #REQUIRED
	negateValue (yes | no) "no"
>
<!-- unordered list -->
<!ELEMENT ul (li | ol | ul)*>
<!ATTLIST ul
	show IDREF #IMPLIED
>
<!ELEMENT useShowWhen EMPTY>
<!ATTLIST useShowWhen
	show IDREF #REQUIRED
>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XMLWriterPracticalDescriptions/WriterPracticalExcl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE portion SYSTEM "..\Data\PAWSSKWriterDescription.dtd">
<portion>
  <section1 id="sExcl">
	 <secTitle>Greetings, Interjections and Exclamations</secTitle>
	<p>
	<content>This section considers various types of common utterances which are not complete sentences.  Greetings, interjections and exclamations are covered in turn.</content>
	</p>
<section2 id="sExclGreet">
	<secTitle>Greetings</secTitle>
<p><content>Greetings typically consist of a particular word or phrase, either standing alone or followed by a name or nominal phrase describing the person or animal being greeted.  Some are full sentences or full questions, such as </content> <langData>How do you do? </langData><langData>How are you? </langData> <content> and </content><langData>Have a good day!</langData> <content> which do not need to be treated separately. </content></p>
   <p><content>Some examples of English greetings are:
   </content><langData>Hi!</langData><content>&#x20;</content><langData>Howdy!</langData><content>&#x20;</content><langData>Goodby</langData><content>, </content><langData>Good day, sir</langData><content> and </content><langData>Good night, sweet baby</langData>
 <content>.</content>
   </p>
<p><content>Examples of greetings in </content><langName/> <content> include:</content></p>
			<example>
				<interlinear exampleLoc="excl/greetExample"/>
			</example>
</section2>
<section2 id="sExclIntj">
	<secTitle>Interjections</secTitle>
<p><content>Interjections typically consist of a particular word or phrase that is used alone, usually with an exclamation point following it.  Though many of the words in interjections are not used in any other situation, regular adjectives are also used in this way.  Some examples of interjections in English are:
</content><langData>Ouch!</langData><content>&#x20;</content><langData>Gross!</langData><content>&#x20;</content><langData>Cool!</langData><content> and </content><langData>Jimminy Cricket!</langData>
</p>

<p><content>Examples of interjections in </content><langName/> <content> include:</content></p>
			<example>
				<interlinear exampleLoc="excl/intjExample"/>
			</example>
<p><content>Yes and No answers to questions are similar to interjections.  </content><langName/><content> uses the following words to express these answers:</content></p>
<example>
<table border="1">
					<headerRow>
						<headerCol>
							<langName/>
						</headerCol>
						<headerCol>Gloss</headerCol>
					</headerRow>
					<row>
						<col exampleLoc="excl/yesExample"/>
						<col>
							<content>yes</content>
						</col>
					</row>
					<row>
						<col exampleLoc="excl/noExample"/>
						<col>
							<content>no</content>
						</col>
					</row>
</table>
</example>
</section2>
<section2 id="sExclExcl">
	<secTitle>Exclamations</secTitle>
<p><content>Exclamations typically consist of a particular word, such as </content><langData>how</langData><content> in English, followed by an adjective phrase and usually punctuated with an exclamation point.  English examples include:</content>
   <langData>How awful for you!</langData><content>&#x20;</content><langData>How nice!</langData><content> and </content><langData>How wonderful that your family could come!</langData>
</p>

<p show="swExclMNo"><langName/><content> does not have a special word which marks exclamations of this type, so they are no different than the interjections consisting of adjectives in the previous section.</content></p>
<p show="swExclMYes"><langName/> <content> has one or more special words which signal an exclamation which occur </content><case element="excl" attr="exclMPos">
<caseText value="before">before</caseText>
<caseText value="after">after</caseText>
<caseText value="either">on either side of</caseText>
<caseText value="both">on both sides of</caseText>
   <caseText value="unknown">________</caseText>
</case><content> the adjective phrase.  </content>
   <text show="swExclMYesEitherNo"><content>There are separate sets words which can occur on each side of the adjective phrase. </content></text>
   <text show="swExclMYesEitherYes"><content>All of the words may occur on either side of the adjective phrase. </content></text>
   <content>These exclamation marker words are:</content></p>
<example show="swExclMYes"><table border="1">
<headerRow>
	<headerCol>Exclamation Markers</headerCol>
	<headerCol>Gloss</headerCol>
</headerRow>
	<row>
		<col exampleLoc="excl/exclMExample"></col>
		<col ><gloss><content>ENTER GLOSS</content></gloss></col>
	</row>
</table>
</example>

   <p><content>Examples of exclamations in </content><langName/><content> include:</content></p>
   <example>
	  <interlinear exampleLoc="excl/exclExample"/>
   </example>
</section2>
  </section1>
<showWhen id="swExclMYes">
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
</showWhen>
<showWhen id="swExclMNo">
	<whenValue element="excl" attr="exclM" value="no"></whenValue>
</showWhen>
<showWhen id="swExclMYesEitherNo">
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMPos" value="either"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMEither" value="no"></whenValue>
<or/>
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMPos" value="both"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMEither" value="no"></whenValue>
</showWhen>
<showWhen id="swExclMYesEitherYes">
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMPos" value="either"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMEither" value="yes"></whenValue>
<or/>
	<whenValue element="excl" attr="exclM" value="yes"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMPos" value="both"></whenValue>
<and/>
	<whenValue element="excl" attr="exclMEither" value="yes"></whenValue>
</showWhen>
</portion>
