=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form, showWhen*)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue), ((or | and), openParen*, not?, (whenRadio | whenValue), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/QPPartitive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="QPPartitive" count="5/7">
	<title level="2">Quantifiers and QP - Partitives</title>
	<introduction>All of the quantifiers, including numbers, can normally occur in <technicalTermRef term="ttPartitive"/> constructions.  These constructions are used to signify that one is talking about just a part of a larger group.  Examples include:
	</introduction>
   <EnglishExample>
      <exItem label="1.">some of the children.</exItem>
      <exItem label="2.">several of the older girls.</exItem>
      <exItem label="3.">many of the women.</exItem>
      <exItem label="4.">just this much of the food.</exItem>
      <exItem label="5.">only ten of the boys.</exItem>
   </EnglishExample>
   <introduction>As the examples show, partitive constructions of this type normally have a prepositional or postpositional phrase modifying the quantifier, which indicates the group or full item being discussed.  Note that in all of these examples, the noun in the partitive phrase can be further modified by a relative clause.<br/><br/>
      Some languages may use a relative clause to express the group of the partitive construction instead of a prepositional or postpositional phrase.
   </introduction>
	<form section="qp">
	   <prompt><br/>Key how your language would express similar kinds of partitive examples with quantifiers here:</prompt>
	   <textBox id="QPPartitiveQExample" dataItem="partitiveQExample"/>
<br/><br/>
	   <radioGroup>
	      <groupName dataItem="partitive" default="no" >RQPPartitive</groupName>
	      <prompt>Based on the examples you keyed, does your language use prepositional or postpositional phrases in partitive constructions?</prompt>
	      <radio id="QPPartitiveYes" dataValue="yes">Yes</radio>
	      <radio id="QPPartitiveNo" dataValue="no">No, a relative clause is used instead</radio>
	      <radio id="QPPartitiveOther" dataValue="other">No, my language uses some other means than either a prepositional or postpositional phrase or a relative clause to express similar meanings</radio>
	   </radioGroup>
	   
	   <radioGroup id="QPPartitivePPPosTable" show="swQPPartitiveYes">
	      <groupName dataItem="partitivePPPos" default="unknown" position="yesHeadDiff">RQPPartitivePPPos</groupName>
	      <prompt>Where does the prepositional or postpositional phrase occur with respect to the quantifier?</prompt>
	      <radio id="QPPartitivePPBefore" checked="yes" dataValue="before">Before the quantifier</radio>
	      <radio id="QPPartitivePPAfter" checked="yes" dataValue="after">After the quantifier</radio>
	      <radio id="QPPartitivePPEitherSide" checked="yes" dataValue="either">On either side</radio>
	   </radioGroup>
	   
	   <prompt id="QPPartitiveOfPrompt" show="swQPPartitiveYes">Key the prepositions or postpositions that can be used to mean “of” in these partitive constructions, with each word on a separate line. </prompt>
	   <textBox id="QPPartitiveOfExample" dataItem="partitiveOf" rows="3" show="swQPPartitiveYes"/>
	   <br/>
	   
	   <prompt id="QPPartitiveRelClPrompt" show="swQPPartitiveNo">The structure of relative clauses will be covered in <section number="12">Relative Clauses</section>.</prompt>
<br/>		<br/>
		<buttons>
			<button id="QPPartitiveBack" value="Back" goto="QPCardinal.xml"/>
		    <button id="QPPartitiveNext" value="Next" goto="QPCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swQPPartitiveNo">
      <whenRadio button="QPPartitiveNo"/>  
   </showWhen> 
   <showWhen id="swQPPartitiveYes">
      <whenRadio button="QPPartitiveYes"/>  
   </showWhen> 
   &TechnicalTerms; 
   
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/IPMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPMain" count="1/1">
    <title level="2">Basic Sentences</title>
   <introduction id="IPMainIntroNotPractical" show="swNotPractical">In this section, we want to handle copular, intransitive, transitive and ditransitive sentences in their basic word order (i.e. not changed by focus, topic, interrogative, or negation constructions).  Inflection and agreement features on verbs, cases when a subject may be missing, auxiliaries, and sentences with passive and other voice changes are also covered.
      <br/>
      <br/>
        The data is in surface form, so the grammar must model surface structure, not the underlying structure before any derivational movement.<br/>
        <br/>
The trees you see will be in an X-bar theory form, as much as is possible for modelling the surface structure without movement.  This means that sentences are Inflectional Phrases (IPs) rather than the traditional S.  The subject usually occupies the specifier position, the head is an inflectional or auxiliary element, and the complement is the VP predicate.  For example, the tree for a transitive sentence in an SVO language, like English will be:
<tree img="TreeDescriptions/PawsIPSVO.png"/>
        <help href="../Help/Cbgbtext.doc#XBarTheory">(Click here to see more on the the IP phrase structure of sentences and X-Bar Theory in general.)</help>
        <br/>
        <br/>
SOV, VOS, and OVS word orders can be handled by taking the mirror image of the appropriate subtrees above.  VSO and OSV word order must have the subject internal to the VP, however, so the flatter structure shown here for VSO word order will be used:
<tree img="TreeDescriptions/PawsIPVSO.png"/>
        <br/>
        <br/>
The basic issues to be dealt with are presented here for your consideration and gathering of appropriate data, then the questions relevant to the basic word order of your language (as determined in section <section number="1">Overall Typology Questions</section>) will deal with the details of setting up the phrase structure rules and lexical features and constraints.
</introduction>
    <introduction id="IPMainIntroPractical" show="swPractical">In this section, we want to handle copular, intransitive, transitive and ditransitive sentences in their basic word order (i.e. not changed by focus, topic, interrogative, or negation constructions).
        <br/>
        <br/>
        Inflection and agreement features on verbs, cases when a subject may be missing, auxiliaries, and sentences with passive and other voice changes are also covered.
    </introduction>
    <form section="ip" transparent="yes">
        <br/>
        <buttons>
            <button id="IPMainBack" value="Back" goto="IPContents.htm"/>
            <button id="IPMainNext" value="Next" goto="IPContents.htm"/>
        </buttons>
    </form>
    <showWhen id="swNotPractical">
        <whenValue  element="paws" attr="outputGrammar" value="True"/>
    </showWhen>
    <showWhen id="swPractical">
        <whenValue  element="paws" attr="outputGrammar" value="False"/>
    </showWhen>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/AdvClMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="AdvClMain" count="1/3">
	<title>Adverbial Clauses</title>
	<introduction>This section considers the complements that can follow temporal and reason adverbs.  Temporal adverbs with complements are used here to illustrate the constructions, then both types will be dealt with for your language on the next screen. </introduction>
	<EnglishExample>
		<exItem>English examples of temporal adverbs with complements used in full sentences include:</exItem>
		<exItem label="1.">[Since then], John has been moody.</exItem>
		<exItem label="2.">John has been home [since last week].</exItem>
		<exItem label="3.">[Since John has been home from the hospital] he is doing better.</exItem>
		<exItem label="4.">John is feeling fine [now that he is home from the hospital].</exItem>
		<exItem label="5.">The dog followed Sue everywhere [when she returned from college].</exItem>
		<exItem label="6."> [When she returned from college], the dog followed Sue everywhere.</exItem>
	</EnglishExample>
	<introduction>These examples show that particular temporal adverbs subcategorize for certain types of complements.  In example 1 <example>since</example> is followed by another temporal adverb, in example 2 by a temporal nominal phrase, and in example 3 it has a sentential complement.  Examples 5 and 6 show that <example>when</example> also takes a sentential complement, whereas <example>now</example> in example 4 has a CP complement.
<br/>
		<br/>
All of these adverbial clauses (or phrases) act the same as simple temporal adverbs, so they will be temporal AdvPs with the appropriate type of complement.  Note also that adverbs of this type normally may occur either sentence-initial or sentence-final.  The tree structures for the first four examples are given here, beginning with the adverb complement (example 1):
<tree img="TreeDescriptions/PawsAdvClAdv.png"/>
		<br/>
The structure with a nominal phrase complement (example 2) is:
		<tree img="TreeDescriptions/PawsAdvClDP.png"/>
		<br/>
The structure with an IP complement (example 3) is:
		<tree img="TreeDescriptions/PawsAdvClIP.png"/>
		<br/>
The structure with an CP complement (example 4) is:
		<tree img="TreeDescriptions/PawsAdvClCP.png"/>
	</introduction>
	<form section="advcl">
		<br/>
		<buttons>
			<button id="AdvClMainBack" value="Back" goto="Contents.htm"/>
			<button id="AdvClMainNext" value="Next" goto="AdvClFeatures.xml"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/es/XmlPageDescriptions/IPIntran.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="IPIntran" count="1/1">
   <title level="2">Las oraciones básicas - Las oraciones intransitivas y de movimiento</title>
   <introduction>Los intransitivos simples no tienen ningún complemento después del verbo, como en <example>La muchacha flota.</example> </introduction>
   <form section="ip">
	  <prompt>Los ejemplos que usted escribió en <section number="1.">La tipología - Sistema de caso</section> de oraciones intransitivas con frases nominales simples o nombres propios como sujetos de verbos que tienen un sujeto-agente se muestran aquí.  Ahora, puede escribir ejemplos adicionales si lo desea.</prompt>
	  <textBox id="IPExamplesIntranExample"  section="typology" dataItem="intExample" cols="50"/>
	  <prompt>Los ejemplos que usted escribió en <section number="1.">La tipología - Sistema de caso</section> de oraciones intransitivas con pronombres independientes como sujetos de verbos que tienen un sujeto-agente se muestran aquí.  Ahora, puede escribir ejemplos adicionales si lo desea.</prompt>
	  <textBox id="IPExamplesIntranPnExample"  section="typology" dataItem="pnIntExample" cols="50"/>
	  <prompt>Los ejemplos que usted escribió en <section number="1.">La tipología - Sistema de caso</section> de oraciones intransitivas con sujetos-experimentadores, con frases nominales simples o nombres propios en la posición del sujeto se muestran aquí.   Ahora, puede escribir ejemplos adicionales si lo desea.</prompt>
	  <textBox id="IPExperiencerIntExample"  section="typology" dataItem="experiencerIntExample" cols="50"/>
	  <prompt>Los ejemplos que usted escribió en <section number="1.">La tipología - Sistema de caso</section>  de oraciones intransitivas con sujetos-experimentadores, con pronombres independientes en la posición del sujeto se muestran aquí.  Ahora, puede escribir ejemplos adicionales si lo desea.</prompt>
	  <textBox id="IPExperiencerPnIntExample"  section="typology" dataItem="experiencerPnIntExample" cols="50"/>
	  <br/>
	  <instruction id="IPIntranExpInstruction" show="swExpNotNo">Since Experiencer subjects are distinct from Agent subjects in your language, add the feature <feature>experiencer</feature> to the verbs which have an Experiencer subject.</instruction>
	  <br/>
	  <introduction> Los verbos de movimiento incluyen un lugar en la forma de una frase preposicional o posposicional o adverbio.  Algunos ejemplos en español con los verbos de movimiento son</introduction>
	  <EnglishExample>
		 <exItem label="1.">La muchacha corrió alrededor de la pista.</exItem>
		 <exItem label="2.">Mi madre fue a la tienda.</exItem>
		 <exItem label="3.">Mi profesor vino aquí.</exItem>
	  </EnglishExample>
	  <prompt>Escriba algunos ejemplos con verbos de movimiento aquí:</prompt>
	  <textBox id="IPExamplesMotionExample" dataItem="motionExample" cols="50"/>
	  <instruction id="IPIntranInstruction">Partial subcategorization can be done as follows, without entering a feature on every verb: if a particular verb is intransitive and can never have anything but a subject, mark it with the feature <feature>intransitive</feature>.  (Don’t consider temporal elements.)  If it is an intransitive motion verb that can have a locative PP or AdvP <span id="IPIntranFollow" show="swHeadInitial">following</span>
		 <span id="IPIntranPrecede" show="swHeadFinal">preceding</span> it, add the feature <feature>motion</feature> to its lexical entry.  Since the motion verbs are a small, closed set, the feature must be entered in the lexicon on the appropriate verbs; the default setting is <feature>-motion</feature>.</instruction>
	  <br/>
	  <br/>
	  <buttons>
		 <button id="IPIntranBack" value="Back" goto="IPContents.htm"/>
		 <button id="IPIntranNext" value="Next" goto="IPContents.htm"/>
	  </buttons>
   </form>
   <showWhen id="swExpNotNo">
	  <not/> <whenValue element="typology" attr="caseExperiencer" value="no"/>
   </showWhen>
   <showWhen id="swHeadInitial">
	  <whenValue element="typology" attr="wordOrder" value="SVO"/>
	  <or/>
	  <whenValue element="typology" attr="wordOrder" value="VOS"/>
	  <or/>
	  <whenValue element="typology" attr="wordOrder" value="VSO"/>
   </showWhen>
   <showWhen id="swHeadFinal">
	  <whenValue element="typology" attr="wordOrder" value="SOV"/>
	  <or/>
	  <whenValue element="typology" attr="wordOrder" value="OVS"/>
	  <or/>
	  <whenValue element="typology" attr="wordOrder" value="OSV"/>
   </showWhen>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/es/XmlPageDescriptions/AdvPDegree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="AdvPDegree" count="5/7">
	<title level="2">Los adverbios y sus frases - Las palabras de grado</title>
	<instruction>Considere otra vez los ejemplos que usted ha escritoo para los varios tipos de frases del adverbio, repetidos a continuación, antes de contestar las preguntas siguientes.</instruction>
	<form section="advp">
		<prompt>Los ejemplos de adverbios de timepo:</prompt>
		<textBox id="AdvPExample" dataItem="temporalExample"/>
		<br/>
		<br/>
		<prompt>Los ejemplos de adverbios de lugar:</prompt>
		<textBox id="AdvPLocExample" dataItem="locativeExample"/>
		<br/>
		<br/>
		<prompt>Los ejemplos de adverbios de manera:</prompt>
		<textBox id="AdvPMannerExample" dataItem="mannerExample"/>
		<br/>
		<br/>
		<prompt>Los ejemplos de adverbios de la razón o del propósito:</prompt>
		<textBox id="AdvPReasonExample" dataItem="reasonExample"/>
		<br/>
		<br/>
		<radioGroup>
			<groupName dataItem="degree" default="no">RDegreeYN</groupName>
			<prompt>¿Hay palabras de grado (escritas como palabras independientes) en su lengua que puedan modificar algunos de los adverbios?</prompt>
			<radio id="AdvPDegreeNo" dataValue="no">No</radio>
			<radio id="AdvPDegreeYes" checked="yes" dataValue="yes">Sí</radio>
			<radioGroup id="AdvPDegreeYesTable" show="swAdvPDegreeYes">
				<groupName dataItem="degreePos" default="unknown" position="yesSpec">RDegree</groupName>
				<prompt>¿Dónde se presentan las palabras de grado con respecto al adverbio?</prompt>
				<radio id="AdvPDegreeBefore" checked="yes" dataValue="before">Antes del adverbio</radio>
				<radio id="AdvPDegreeAfter" checked="yes" dataValue="after">Después del adverbio</radio>
				<radio id="AdvPDegreeEitherSide" checked="yes" dataValue="either">De cualquier lado del adverbio, pero en no ambos lados en la misma oración</radio>
				<radio id="AdvPDegreeEitherOrBoth" checked="yes" dataValue="eitherOrBoth">De cualquier lado del adverbio, o en ambos lados en la misma oración</radio>
				<radio id="AdvPDegreeBeforeOrBoth" checked="yes" dataValue="beforeOrBoth">Antes del adverbio, o en ambos lados en la misma oración</radio>
				<radio id="AdvPDegreeAfterOrBoth" checked="yes" dataValue="afterOrBoth">Después del adverbio, o en ambos lados en la misma oración</radio>
				<radio id="AdvPDegreeBothSides" checked="yes" dataValue="both">Solamente en ambos lados en la misma oración</radio>
				<radioGroup id="AdvPDegreeEitherSideTable" show="swAdvPDegreeEitherorBoth">
					<groupName dataItem="degreeEither" default="unrestricted">RDegreeEitherSide</groupName>
					<prompt>¿Pueden presentarse todas las palabras de grado de cualquier lado del adverbio?</prompt>
					<radio id="AdvPDegreeEitherUnrestricted" checked="yes" dataValue="unrestricted">Sí, no hay restricción</radio>
					<radio id="AdvPDegreeEitherRestricted" checked="yes" dataValue="restricted">No, hay distintos grupos para cada lado</radio>
				</radioGroup>
			</radioGroup>
			<radioGroup id="AdvPDegreeSetTable" show="swAdvPDegreeYes">
				<groupName dataItem="degreeSet" default="unrestricted">RSet</groupName>
				<prompt>¿Son las palabras de grado que pueden modificar adverbios todas las mismas?</prompt>
				<radio id="AdvPSetUnrestricted" checked="yes" dataValue="unrestricted">Sí, el mismo grupo puede modificar cualquier tipo de adverbio</radio>
				<radio id="AdvPSetAlmost" checked="yes" dataValue="exceptReason">Casi; el mismo grupo puede modificar adverbios de tiempo, adverbios de lugar y adverbios de manera, pero los adverbios de razón o propósito no se modifican</radio>
				<radio id="AdvPSetRestricted" checked="yes" dataValue="restricted">No, hay distintos grupos de las palabras de grado para cada tipo de adverbio (nota que algo traslapo es aceptable y ningunas palabras de grado para los adverbios de razón o propósito es también aceptable)
</radio>
			</radioGroup>
		</radioGroup>
		<instruction id="AdvPDegreeInstruction">
			<span id="AdvPSetUnrestrictedInstruction" show="swAdvPSetUnrestricted">Key the features <feature>makeDeg modifies_Adv</feature> on this type of degree word in the lexicon.    (If any of these degree words are the same as those which can modify an entire nominal phrase or a quantifier, you can simply add the additional feature <feature>modifies_Adv</feature> to the same lexical entry.)</span>
			<span id="AdvPSetAlmostInstruction" show="swAdvPSetAlmost">Key the features <feature>makeDeg modifies_Adv-reason</feature> on this type of degree word in the lexicon.    (If any of these degree words are the same as those which can modify an entire nominal phrase or a quantifier, you can simply add the additional feature <feature>modifies_Adv-reason</feature> to the same lexical entry.)
</span>
			<span id="AdvPSetRestrictedInstruction" show="swAdvPSetRestricted">In the lexicon, key the features:
<ul>
					<li>
						<feature>makeDeg modifies_temporal</feature> for temporal modifiers,</li>
					<li>
						<feature>makeDeg modifies_locative</feature> for locative modifiers,</li>
					<li>
						<feature>makeDeg modifies_manner</feature> for manner modifiers, and</li>
					<li>
						<feature>makeDeg modifies_reason</feature> for reason or purpose modifiers</li>
				</ul>
 If you have overlapping in the sets, just add more than one <feature>modifies...</feature> feature after a space.    (Similarly, if any of these degree words are the same as those which can modify an entire nominal phrase or a quantifier, you can simply add the additional <feature>modifies...</feature> feature(s) to the same lexical entry.)  If there are no degree words which modify reason or purpose adverbs, just don’t mark any words with this feature.</span>
			<br/>
			<br/>
			<span id="AdvPDegreeEitherRestrictedInstruction" show="swAdvPDegreeEitherRestricted">
Those which can only occur before the adverb
also need to have the feature <feature>AdvP-initial</feature>
and those which can only occur after the adverb also need the
feature <feature>AdvP-final</feature>.  Do not enter either
feature <feature>AdvP-initial</feature> or <feature>AdvP-final</feature> on any degree words which can occur on
either side.</span>
		</instruction>
		<br/>
		<buttons>
			<button id="AdvPDegreeBack" value="Back" goto="AdvPReason.xml"/>
			<button id="AdvPDegreeNext" value="Next" goto="AdvPCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
	<showWhen id="swAdvPDegreeYes">
		<whenRadio button="AdvPDegreeYes"/>
	</showWhen>
	<showWhen id="swAdvPDegreeEitherorBoth">
		<whenRadio button="AdvPDegreeYes"/>
		<and/>
		<not/>
		<whenRadio button="AdvPDegreeBefore"/>
		<and/>
		<not/>
		<whenRadio button="AdvPDegreeAfter"/>
	</showWhen>
	<showWhen id="swAdvPDegreeEitherRestricted">
		<whenRadio button="AdvPDegreeYes"/>
		<and/>
		<whenRadio button="AdvPDegreeEitherRestricted"/>
		<and/>
		<not/>
		<whenRadio button="AdvPDegreeBefore"/>
		<and/>
		<not/>
		<whenRadio button="AdvPDegreeAfter"/>
	</showWhen>
	<showWhen id="swAdvPSetUnrestricted">
		<whenRadio button="AdvPDegreeYes"/>
		<and/>
		<whenRadio button="AdvPSetUnrestricted"/>
	</showWhen>
	<showWhen id="swAdvPSetAlmost">
		<whenRadio button="AdvPDegreeYes"/>
		<and/>
		<whenRadio button="AdvPSetAlmost"/>
	</showWhen>
	<showWhen id="swAdvPSetRestricted">
		<whenRadio button="AdvPDegreeYes"/>
		<and/>
		<whenRadio button="AdvPSetRestricted"/>
	</showWhen>
</page>
