=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form, showWhen*)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue), ((or | and), openParen*, not?, (whenRadio | whenValue), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/PronNP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="PronNP" count="7/9">
	<title level="2">Pronouns - As a Nominal Phrase</title>
   <introduction>Pronouns of all types normally stand alone in the place of an entire nominal phrase, but they can also be modified by a relative clause. In some languages pronouns may be modified by partitive phrases, and other languages allow pronouns to also be modified by <technicalTermRef term="ttDeterminers"/> and wide scope quantifiers and degree words. English examples of this type include the following:</introduction>
		<EnglishExample>
			<exItem label="1.">just we three</exItem>
			<exItem label="2.">only he</exItem>
		   <exItem label="3.">only these</exItem>
		</EnglishExample>
   <introduction>In fewer languages, pronouns can also be modified by adjectives and possessors, acting just like nouns.</introduction>
   <form section="pron">
      <radioGroup>
         <groupName dataItem="pronMod" default="no">RPronMod</groupName>
         <prompt><br/>Can pronouns be modified in your language?</prompt>
         <radio id="PronModNo" dataValue="no">No, these elements only appear by themselves when they take the place of a nominal phrase.  Not even relative clauses are allowed as modifiers </radio>
         <radio id="PronModRel" dataValue="rel">Only relative clauses are possible</radio>
         <radio id="PronModPart" dataValue="part">Only relative clauses and partitive phrases are allowed</radio>
         <radio id="PronModDet" dataValue="det">Yes, these elements can be modified by the wide scope quantifiers and degree words <span id="PronModDetArtSpan"  show="swArt">and articles</span><span id="PronModDetDemSpan" show="swDem">and demonstratives</span ><span id="PronModArtDemSpan" show="swArtAndDem">and articles and demonstratives</span> in addition to relative clauses and partitive phrases</radio>
     <radio id="PronModAll" dataValue="all">Yes, these elements can be modified by all the same modifiers as nouns can, including adjectives and possessors</radio>
      </radioGroup>   
      <prompt id="PronModMinimalExamplePrompt" show="swPronModDetOrAll">Key examples from your language of pronouns modified by some or all of the allowed elements here:</prompt>
		<textBox id="PronNPStandAloneExample" dataItem="standAloneNPExample" show="swPronModDetOrAll"/>
      <prompt id="PronModSentExamplePrompt" show="swPronModDetOrAll">Now take several of the examples you keyed in the textbox above and use them as the subject or object of a sentence here:</prompt>
      
      <br/><br/>
      <introduction>In addition, pronouns can usually be modified by a partitive phrase (or other PP), as in:</introduction>
      <EnglishExample>
         <exItem label="4.">you in there</exItem>
         <exItem label="5.">we of this state</exItem>
         <exItem label="6.">those of you from that school</exItem>
      </EnglishExample>
      <br/>
      <prompt id="PronNPPartitiveModNo" show="swPronModNoOrRel">We assume this is not possible in your language, based on your answer above.  If this is incorrect, please change your answer above.</prompt>
      <prompt id="PronNPPartitiveMod" show="swPronModNotNoOrRel">Key your examples here:</prompt>
      <textBox id="PronNPPartitiveExample" dataItem="partitiveExample" show="swPronModNotNoOrRel"/>
      <br/>
      <radioGroup id="PronNPPartitiveTable" show="swPronModNotNoOrRel">
         <groupName dataItem="partitivePos" default="unknown" position="yesHeadDiff">RPronNPPartitive</groupName>
         <prompt>Where does the optional PP occur with respect to the pronoun?</prompt>
         <radio id="PronNPPartBefore" dataValue="before">Before</radio>
         <radio id="PronNPPartAfter" dataValue="after">After</radio>
         <radio id="PronNPPartEither" dataValue="either">On either side</radio>
      </radioGroup>
      <br/><br/>
      <introduction>Finally, it is usually possible to have a pronoun modified by a relative clause, as in:</introduction>
		<EnglishExample>
			<exItem label="7.">you who are going with us</exItem>
		   <exItem label="8.">everyone who wants to come</exItem>
		   <exItem label="9.">we who believe</exItem>
		</EnglishExample>
		<br/>
      <prompt id="PronNPRelModNo" show="swPronModNo">We assume this is not possible in your language, based on your answer above.  If this is incorrect, please change your answer above.</prompt>
      <prompt id="PronNPRelClMod" show="swPronModNotNo">Key your examples with relative clauses, placing these nominal phrases as the subject or object of a simple sentence, here:</prompt>
		<textBox id="PronNPRelCl" dataItem="pronRelClExample" show="swPronModNotNo"/>
		<br/>
      <instruction id="PronDistributionNPInstruction" show="swNotPracticalAndPronModDet">In the tree structure given at the beginning of <section number="5">Nominal Phrases</section>, we will assume for your language that pronouns can fill the NP position, because they can be modified by degree words, demonstratives, articles, relative clauses and PPs, but not by possessors or adjectives.</instruction>
      <instruction id="PronDistributionNPPartInstruction" show="swNotPracticalAndPronModPart">In the tree structure given at the beginning of <section number="5">Nominal Phrases</section>, we will assume for your language that pronouns can fill the NP position, because they can be modified by relative clauses and PPs.</instruction>
      <instruction id="PronDistributionNInstruction" show="swNotPracticalAndPronModAll">In the tree structure given at the beginning of <section number="5">Simple and Possessed Nominal Phrases</section>, we will assume for your language that pronouns can fill the N position, because they can be modified by all the same categories as nouns can.</instruction>
      <instruction id="PronDistributionDPInstruction" show="swNotPracticalAndPronModNoOrRel">In the tree structure given at the beginning of <section number="5">Simple and Possessed Nominal Phrases</section>, we will assume for your language that pronouns can fill the DP position, because they must stand alone in the place of a whole nominal phrase, or possibly be modified by a relative clause.</instruction>  
		<br/><br/>
		<buttons>
			<button id="PronNPBack" value="Back" goto="PronIndefinite.xml"/>
		    <button id="PronNPNext" value="Next" goto="PronCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
	<showWhen id="swNotPractical">
		<whenValue  element="paws" attr="outputGrammar" value="True"/>
	</showWhen>
   <showWhen id="swArt">
      <whenValue element="np" attr="artAndDem" value="article"/>
   </showWhen>
   <showWhen id="swDem">
      <whenValue element="np" attr="artAndDem" value="demonstrative"/>
   </showWhen>
   <showWhen id="swArtAndDem">
      <whenValue element="np" attr="artAndDem" value="both"/>
   </showWhen>
   <showWhen id="swPronModNotNo">
      <not/><whenRadio button="PronModNo"/>
   </showWhen>
   <showWhen id="swPronModNo">
      <whenRadio button="PronModNo"/>
   </showWhen>
   <showWhen id="swNotPracticalAndPronModDet">
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModDet"/>
   </showWhen> 
   <showWhen id="swNotPracticalAndPronModAll">
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModAll"/>
   </showWhen> 
   <showWhen id="swNotPracticalAndPronModNo">
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModNo"/>
   </showWhen> 
   <showWhen id="swNotPracticalAndPronModPart">
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModPart"/>
   </showWhen>
   <showWhen id="swNotPracticalAndPronModNoOrRel">
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModNo"/>
      <or/>
      <whenValue  element="paws" attr="outputGrammar" value="True"/>
      <and/>
      <whenRadio button="PronModRel"/>
   </showWhen>
<showWhen id="swPronModNoOrRel">
   <whenRadio button="PronModNo"/>
   <or/>
   <whenRadio button="PronModRel"/>
   </showWhen>
   <showWhen id="swPronModNotNoOrRel">
      <not/><whenRadio button="PronModNo"/>
      <and/><not/>
      <whenRadio button="PronModRel"/>
   </showWhen>
   <showWhen id="swPronModDetOrAll">
      <whenRadio button="PronModDet"/>
      <or/>
      <whenRadio button="PronModAll"/>
   </showWhen>
   
   &TechnicalTerms; 
   
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/QMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QMain" count="1/9">
	<title>Questions</title>
	<introduction id="QMainIntroNotPractical" show="swNotPractical">This section considers the main clause and embedded clause varieties of Yes/No questions and content questions.  We will begin with Yes/No questions.
<br/>
		<br/>
 In English, main clause Yes/No questions are formed by moving an auxiliary verb in front of the subject.  Other languages use a Yes/No question marker or special complementizer instead of the fronted auxiliary.  This is the case in embedded Yes/No questions in English; no auxiliary fronting is allowed but <example>whether</example> or <example>if</example> fills the complementizer position.<br/>
		<br/>
As discussed in <section number="10">Complement Clauses</section>, X-bar theory takes the complementizer to be the head of the phrase, so a CP sits on top of the IP for questions even in main clauses.  Sample trees for main clause and embedded Yes/No questions in English are shown here:
<tree img="TreeDescriptions/PawsMainYNQues.png"/>
		<br/>
		<tree img="TreeDescriptions/PawsEmbYNQues.png"/>
		<br/>
		<help href="Help/Cbgbtext.doc#CPYesNoQuestions">Click here for more information about the CP phrase structure of Yes/No questions.</help>
	   <br/><br/>Since a language may act differently  in Yes/No questions in the main clause versus subordinate clauses, each type will be discussed separately.
	</introduction>
	<introduction id="QMainIntroPractical" show="swPractical">This section considers the main clause and embedded clause varieties of Yes/No questions and content questions.  We will begin with Yes/No questions.
		<br/>
		<br/>
		In English, main clause Yes/No questions are formed by moving an auxiliary verb in front of the subject.  Other languages use a Yes/No question marker or special complementizer instead of the fronted auxiliary.  This is the case in embedded Yes/No questions in English; no auxiliary fronting is allowed but <example>whether</example> or <example>if</example> fills the complementizer position.<br/>
	   <br/><br/>Since a language may act differently  in Yes/No questions in the main clause versus subordinate clauses, each type will be discussed separately.
	</introduction>
	<form section="q" transparent="yes">
		<br/>
		<buttons>
			<button id="QMainBack" value="Back" goto="Contents.htm"/>
			<button id="QMainNext" value="Next" goto="QMainYN.xml"/>
		</buttons>
	</form>
	<showWhen id="swNotPractical">
		<whenValue  element="paws" attr="outputGrammar" value="True"/>
	</showWhen>
	<showWhen id="swPractical">
		<whenValue  element="paws" attr="outputGrammar" value="False"/>
	</showWhen>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/PPCatMap.xml
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="PPCatMap" count="4/5">
	<title level="2">Pre/Post-Positional Phrases - Category Mapper</title>
	<form section="pp">
		<instruction>
			<span id="PPWordCategorySpan" show="swPPWord">You need to make sure the <span id="PPPrepSpanT1" show="swPPPosPrep">prepositions</span>
				<span id="PPPostSpanT1" show="swPPPosPost">postpositions</span>
				<span id="PPBothSpanT1" show="swPPPosBoth">prepositions and postpositions</span> in your lexicon will be mapped to the syntax category <category>P</category>.  Note that this only applies to <span id="PPPrepSpanT2" show="swPPPosPrep">prepositions</span>
				<span id="PPPostSpanT2" show="swPPPosPost">postpositions</span>
				<span id="PPBothSpanT2" show="swPPPosBoth">prepositions and postpositions</span> which stand alone as independent syntactic words; any clitic forms have already been marked appropriately.  Choose one of the following options, depending on your situation:
<ul>
					<li>If you already have <span id="PPPrepSpanT3" show="swPPPosPrep">prepositions</span>
						<span id="PPPostSpanT3" show="swPPPosPost">postpositions</span>
						<span id="PPBothSpanT3" show="swPPPosBoth">prepositions and postpositions</span> marked with the category <category>P</category> in your lexicon nothing more needs to be done.</li>
					<li>If <span id="PPPrepSpanT4" show="swPPPosPrep">prepositions</span>
						<span id="PPPostSpanT4" show="swPPPosPost">postpositions</span>
						<span id="PPBothSpanT4" show="swPPPosBoth">prepositions and postpositions</span> are mixed in with another category in the lexicon, you either need to give them the category <category>P</category> in your morphological parser, or add the feature <feature>makeP</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.  (If a particular entry can also be used as another syntactic category, make a separate lexical entry for each use.)</li>
					<li>If you have <span id="PPPrepSpanT5" show="swPPPosPrep">prepositions</span>
						<span id="PPPostSpanT5" show="swPPPosPost">postpositions</span>
						<span id="PPBothSpanT5" show="swPPPosBoth">prepositions and postpositions</span> marked in your lexicon with a distinct category all their own, but it is different from <category>P</category>, enter that category below so PAWS can map your morphological category to <category>P</category>. <br/>
						<catMap id="PPPCategory" dataItem="pCategory">P</catMap>
					</li>
				</ul>
			</span>
			<span id="PPCliticOnlySpan" show="swPPClitic">Since all your <span id="PPPrepSpanT6" show="swPPPosPrep">prepositions</span>
				<span id="PPPostSpanT6" show="swPPPosPost">postpositions</span>
				<span id="PPBothSpanT6" show="swPPPosBoth">prepositions and postpositions</span> are clitics, category mapping is not needed.</span>
		</instruction>
			<br/>
		<br/>
		<buttons>
			<button id="PPCatMapBack" value="Back" goto="PPOther.xml"/>
			<button id="PPCatMapNext" value="Next" goto="PPTesting.xml"/>
		</buttons>
	</form>
	<showWhen id="swPPWord">
		<not/>
		<whenValue element="pp" attr="pType" value="clitic"/>
	</showWhen>
	<showWhen id="swPPClitic">
		<whenValue element="pp" attr="pType" value="clitic"/>
	</showWhen>
	<showWhen id="swPPPosPrep">
		<whenValue element="pp" attr="pPos" value="before"/>
	</showWhen>
	<showWhen id="swPPPosPost">
		<whenValue element="pp" attr="pPos" value="after"/>
	</showWhen>
	<showWhen id="swPPPosBoth">
		<whenValue element="pp" attr="pPos" value="both"/>
	</showWhen>
</page>

=== sillsdev/CarlaLegacy/PAWS/XMLPageDescriptions/NPCatMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="NPCatMap">
	<title level="2">Nominal Phrases - Category Mapper</title>
	<form section="np">
		<instruction id="NPArtCategoryInstruction" show="swNPArt">You need to make sure the articles in your lexicon will be mapped to the syntactic category <category>Art</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have articles marked with the category <category>Art</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If articles are mixed in with another category in the lexicon, you either need to give them the category <category>Art</category> in your morphological parser, or add the feature <feature>makeArt</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have articles marked in your lexicon with a distinct category all their own, but it is different from <category>Art</category>, enter that category below so PAWS can map your morphological category to <category>Art</category>. <br/>
					<catMap id="NPArticleCategory" dataItem="articleCategory">Art</catMap>
				</li>
			</ul>
		</instruction>
		<instruction id="NPDemCategoryInstruction" show="swNPDem">You need to make sure the demonstratives in your lexicon will be mapped to the syntactic category <category>Dem</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have demonstratives marked with the category <category>Dem</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If demonstratives are mixed in with another category in the lexicon, you either need to give them the category <category>Dem</category> in your morphological parser, or add the feature <feature>makeDem</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have demonstratives marked in your lexicon with a distinct category all their own, but it is different from <category>Dem</category>, enter that category below so PAWS can map your morphological category to <category>Dem</category>. <br/>
					<catMap id="NPDemonstrativeCategory" dataItem="demonstrativeCategory">Dem</catMap>
				</li>
			</ul>
		</instruction>
		<instruction id="NPNounCategoryInstruction">You need to make sure the nouns in your lexicon will be mapped to the syntactic category <category>N</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have nouns marked with the category <category>N</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If nouns are mixed in with another category in the lexicon, you either need to give them the category <category>N</category> in your morphological parser, or add the feature <feature>makeN</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have nouns marked in your lexicon with a distinct category all their own, but it is different from <category>N</category>, enter that category below so PAWS can map your morphological category to <category>N</category>. <br/>
					<catMap id="NPNounCategory" dataItem="nounCategory">N</catMap>
				</li>
			</ul>
		</instruction>
<br/>
		<br/>
		<buttons>
			<button id="NPCatMapBack" value="Back" goto="NPContents.htm"/>
			<button id="NPCatMapNext" value="Next" goto="NPContents.htm"/>
		</buttons>
	</form>
	<showWhen id="swNPArt">
		<whenValue element="np" attr="artAndDem" value="article"/>
		<or/>
		<whenValue element="np" attr="artAndDem" value="both"/>
	</showWhen>
	<showWhen id="swNPDem">
		<whenValue element="np" attr="artAndDem" value="demonstrative"/>
		<or/>
		<whenValue element="np" attr="artAndDem" value="both"/>
	</showWhen>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/LangProp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="LangProp">
	<title level="2">Language Properties</title>
	<introduction>The PAWS Starter Kit is for a particular language.  Certain
information is needed.  Please enter the appropriate information
below.</introduction>
	<form section="language">
		<prompt>Enter the name of your language:</prompt>
		<textBox id="LangPropLangName" dataItem="langName" cols="50" rows="1"/>
		<prompt>Enter an abbreviation for your language (we suggest using the Ethnologue or ISO639-3 code):</prompt>
		<textBox id="LangPropLangAbbr" dataItem="langAbbr" cols="4" rows="1"/>
		<font id="LangPropFont" dataItem="font">
		<prompt>The name of the font that will be used to display your language data is shown below.  Click on the 'Change font' button to change it.</prompt></font>
		<radioGroup>
			<groupName dataItem="rtl" default="False">RLangPropRTL</groupName>
			<prompt>In what direction is your language written?</prompt>
			<radio id="LangPropRTLLTR" dataValue="False">Left to right</radio>
			<radio id="LangPropRTLRTL" dataValue="True">Right to left</radio>
		</radioGroup>
		<buttons>
			<button id="LangPropBack" value="Back" goto="LeftOffAt.htm"/>
			<button id="LangPropNext" value="Next" goto="LeftOffAt.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/PAWS/XMLPageDescriptions/QPCatMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QPCatMap">
	<title level="2">Quantifiers and QP - Category Mapper</title>
	<form section="qp">
		<instruction>You need to make sure the cardinal number words in your lexicon will be mapped to the syntactic category <category>Num</category> (including the same capitalization).  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have numbers marked with the category <category>Num</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If numbers are mixed in with another category in the lexicon (e.g. adjectives), you either need to give them the category <category>Num</category> in your morphological parser, or add the feature <feature>makeNum</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have numbers marked in your lexicon with a distinct category all their own, but it is different from <category>Num</category>, enter that category below so PAWS can map your morphological category to <category>Num</category>. <br/>
					<catMap id="QPCardinalNumberCategory" dataItem="cardinalNumberCategory">Num</catMap>
				</li>
			</ul>
			<br/>
		You need to make sure the conjunctions in your lexicon will be mapped to the syntactic category <category>Conj</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have conjunctions marked with the category <category>Conj</category> in your lexicon, nothing more needs to be done.</li>
				<li>If conjunctions are mixed in with another category in the lexicon, you either need to give them the category <category>Conj</category> in your morphological parser, or add the feature <feature>makeConj</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have conjunctions marked in your lexicon with a distinct category all their own, but it is different from <category>Conj</category>, enter that category below so PAWS can map your morphological category to <category>Conj</category>. <br/>
					<catMap id="QPConjunctionCategory" dataItem="conjunctionCategory">Conj</catMap>
				</li>
			</ul>
</instruction>			<br/>
		<br/>
		<buttons>
			<button id="QPCatMapBack" value="Back" goto="QPCardinal.htm"/>
			<button id="QPCatMapNext" value="Next" goto="QPTesting.htm"/>
		</buttons>
</form>
</page>
