=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Data/PAWSSKHtmlMapper.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<!-- DTD for PAWS Starter Kit XML to HTML and code mappers -->
<!ENTITY nbsp "&#160;">
<!ENTITY % embedded "#PCDATA | a | br | category | catMap | contents | example | feature |
						 featureChart | file | help | i | ol | p | section | span |
			 template | templateName | tool | tree | u | ul">
<!ELEMENT a (%embedded;)*>
<!ATTLIST a
	href CDATA #REQUIRED
	target CDATA #IMPLIED
>
<!ELEMENT and EMPTY>
<!ELEMENT br EMPTY>
<!ELEMENT button EMPTY>
<!ATTLIST button
	id ID #REQUIRED
	value (Back | Next | Yes | No) #REQUIRED
	goto CDATA #IMPLIED
	gotoNoGrammar CDATA #IMPLIED
	>
<!ELEMENT buttons (button, codeInfo?, ruleInfo?, button, codeInfo?, ruleInfo?)>
<!ELEMENT category (#PCDATA)>
<!-- content is the name of the syntactic category -->
<!ELEMENT catMap (#PCDATA)>
<!ATTLIST catMap
	id ID #REQUIRED
	dataItem CDATA #REQUIRED
>
<!ELEMENT closeParen EMPTY>
<!ELEMENT codeInfo (#PCDATA)>
<!ELEMENT contents (#PCDATA)>
<!ELEMENT div (textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*>
<!ATTLIST div
	id ID #REQUIRED
	show IDREF #REQUIRED
>
<!ELEMENT EnglishExample (exItem+)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT exItem (#PCDATA | span | u | sub)*>
<!ATTLIST exItem
	label CDATA #IMPLIED
>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT featureChart (featureRow)+>
<!ATTLIST featureChart
	types (yes | no) "yes"
	explanations (yes | no) "yes"
>
<!ELEMENT featureExplanation (#PCDATA)>
<!ELEMENT featureItem (#PCDATA)>
<!ATTLIST featureItem
	dataValue CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT featureRow (featureType?, featureItem, featureExplanation)+>
<!ELEMENT featureType (#PCDATA)>
<!ATTLIST featureType
	rowspan CDATA #IMPLIED
>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	id ID #REQUIRED
	section CDATA #REQUIRED
>
<!--
transparent = 'yes' means do not show yellow background, let the grey background come through.
-->
<!ELEMENT form ((textBox | prompt | radioGroup | instruction | codeInfo | ruleInfo | introduction | EnglishExample | br | div)*, br?, buttons)>
<!ATTLIST form
	transparent (yes | no) "no"
	section CDATA #REQUIRED
>
<!ELEMENT help (#PCDATA)>
<!ATTLIST help
	href CDATA #REQUIRED
>
<!ELEMENT i (#PCDATA)>
<!ELEMENT groupName (#PCDATA)>
<!ATTLIST groupName
	dataItem CDATA #REQUIRED
	default CDATA #REQUIRED
	position (no | yesSpec | yesHead | yesHeadDiff) "no"
>
<!ELEMENT instruction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST instruction
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT introduction (%embedded; | codeInfo | ruleInfo)*>
<!ATTLIST introduction
	transparent (yes | no) "yes"
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT li (%embedded;)*>
<!ATTLIST li
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT not EMPTY>
<!ELEMENT ol (li+)>
<!ELEMENT p (%embedded;)*>
<!ATTLIST p
	style CDATA #IMPLIED
>
<!ELEMENT openParen EMPTY>
<!ELEMENT or EMPTY>
<!ELEMENT page (title, (introduction | EnglishExample | instruction)*, form, showWhen*)>
<!ATTLIST page
	id ID #REQUIRED
	count CDATA #IMPLIED
>
<!ELEMENT prompt (%embedded;)*>
<!ATTLIST prompt
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radio (%embedded;)*>
<!ATTLIST radio
	id ID #REQUIRED
	dataValue CDATA #REQUIRED
	checked (yes) #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT radioGroup (groupName, prompt, radio, (radio | codeInfo | ruleInfo | radioGroup)*)>
<!ATTLIST radioGroup
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT ruleInfo (#PCDATA)>
<!ELEMENT span (%embedded;)*>
<!ATTLIST span
	id ID #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT section (#PCDATA)>
<!ATTLIST section
	number CDATA #REQUIRED
>
<!ELEMENT showWhen (openParen*, not?, (whenRadio | whenValue), ((or | and), openParen*, not?, (whenRadio | whenValue), closeParen*)*, closeParen*)>
<!ATTLIST showWhen
	id ID #REQUIRED
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT textBox EMPTY>
<!ATTLIST textBox
	id ID #REQUIRED
	contenteditable (true | inherit | false) "inherit"
	dataItem CDATA #REQUIRED
	section CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	show IDREF #IMPLIED
>
<!ELEMENT title (#PCDATA | i)*>
<!ATTLIST title
	level CDATA #IMPLIED
>
<!ELEMENT template (#PCDATA)>
<!ELEMENT templateName (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT tree (#PCDATA | br)*>
<!ATTLIST tree
	img CDATA #IMPLIED
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT whenRadio EMPTY>
<!ATTLIST whenRadio
	button IDREF #REQUIRED
>
<!ELEMENT whenValue EMPTY>
<!ATTLIST whenValue
	element CDATA #REQUIRED
	attr CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/NPTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="NPTesting" count="1/1">
	<title level="2">Nominal Phrases - Testing</title>
	<form section="np">
		<instruction>To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
	<br/>
	<br/>
Run the file <file id="NPTestingFile" section="np">xxxNPTest.txt</file> through your morphological parser and then
run the syntactic parser on the output (all possible within CarlaStudio, as noted on the 'Contents' page).  Check the log for the
results and note any changes you need to make, most likely by adding features to particular entries in the lexicon.  If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, so you need to fix the problem with the morphlogical parser first.  You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.   Or you may need to use the Category Mapper on the previous page to correct differences between your categories and those used by PAWS.  Make the changes as needed.  If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  Rerun the parsers and check the results again.<br/>
			<br/>
(Note:  some examples cannot be tested until you complete <section number="8">Pre/Post-positional Phrases</section> or <section number="12">Relative Clauses</section> so they will appear in <file id="PPTestingFile" section="pp">xxxPPTest.txt</file> or <file id="RelClTestingFile" section="relcl">xxxRelClTest.txt</file> instead of this file.)<br/>
				<br/>
Please check off this section now in 'Contents' and then proceed to
<section number="6">Proper Names</section> when you are ready.
		</instruction>
	<br/>
		<br/>
		<buttons>
			<button id="NPTestingBack" value="Back" goto="NPContents.htm"/>
			<button id="NPTestingNext" value="Next" goto="NPContents.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/es/XmlPageDescriptions/PNMain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="PNMain" count="1/3">
	<title>Los nombres propios</title>
   <introduction> Los nombres propios son una clase especial de sustantivos o frases nominalesque sintácticamente funcionan igual que otros sustantivos o frases nominales. En español, algunos nombres propios pueden presentarse solos, como  <example>Susana</example> y <example>Oaxaca</example>.  Otros funcionan como sustantivos compuestos, como <example>George Washington</example>.  Los nombres propios también pueden contener los artículos y/o <technicalTermRef term="ttAdpositionalPhrases"/>, como en <example>los Estados Unidos de América</example>.  Muchas lenguas requieren un artículo antes de un nombre. Appositives, posiblemente incluyendo un posesivo, como en <example>mi hijo, David</example>, también ocurren, pero apositivos se tratan más adelante en <section number="15."> Las construcciones coordinadas</section>.  Además, los nombres propios se pueden modificar por los adjetivos y cláusulas relativas, como en <example>México fuerte y orgulloso</example> o <example>la Susana que conozco</example>.</introduction>
	<form section="prop">
		<prompt>Escriba sus ejemplos nombres propios simples y compuestos, o los que se presentan con artículos, demonstratives, adjetivos o los posesivos aquí :</prompt>
		<textBox id="PNExample" dataItem="example"/>
	   <br/><br/>
	   <radioGroup id="PNClassifiersTable" show="swOTClassifierAgr">
	      <groupName dataItem="pnClassifier" default="no">RPNClassifiers</groupName>
	      <prompt>Usted dijo que su lengua tiene clasificadores que indican la concordancia en las frases nominales. ¿Utiliza los clasificadores para marcar los nombres propios también?</prompt>
	      <radio id="PNClassifiersNo" dataValue="no">No, los nombres propios no se marcan con clasificadores</radio>
	      <radio id="PNClassifiersYes" dataValue="yes">Sí, los nombres propios se marcan con clasificadores lo mismo que sustantivos</radio>
	   </radioGroup>
	   <radioGroup id="PNDeterminersTable" show="swNPArtAndDemNotNo">
	      <groupName dataItem="pnDeterminer" default="no">RPNDeterminer</groupName>
	      <prompt>¿Se requieren los nombres propios en su lengua contener <span id="PNArtOnlySpan" show="swNPArtAndDemArt">un artículo</span>
	         <span id="PNDemOnlySpan" show="swNPArtAndDemDem">un demostrativo</span><span id="PNArtAndDemSpan" show="swNPArtAndDemBoth">un artículo o un demostrativo</span> o un posesivo?</prompt>
	      <radio id="PNDeterminerNo" dataValue="no">No, pueden contener estos elementos pero no son requiridos</radio>
	      <radio id="PNDeterminerYes" dataValue="yes">Sí, cada nombre propio debe contener al menos uno de estos elementos</radio>
	   </radioGroup>
	   <br/>
		<br/>
		<prompt>Escriba sus ejemplos de nombres propios con frases adposicionales aquí:</prompt>
		<textBox id="PNPPExample" dataItem="ppExample"/>
		<br/>
		<br/>
	   <prompt>Escriba sus ejemplos de oraciones completas (pero simples) con los nombres propios modificados con las cláusulas relativas aquí:</prompt>
		<textBox id="PNRelClExample" dataItem="relClExample"/>
		<br/>
		<br/>
		<buttons>
			<button id="PNMainBack" value="Back" goto="Contents.htm"/>
		    <button id="PNMainNext" value="Next" goto="PNCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swOTClassifierAgr">
      <whenValue element="typology" attr="classifier" value="yesAgr"/>   
   </showWhen>
   <showWhen id="swNPArtAndDemArt">
      <whenValue element="np" attr="artAndDem" value="article"/>
   </showWhen>
   <showWhen id="swNPArtAndDemDem">
      <whenValue element="np" attr="artAndDem" value="demonstrative"/>
   </showWhen>
   <showWhen id="swNPArtAndDemBoth">
      <whenValue element="np" attr="artAndDem" value="both"/>
   </showWhen>
   <showWhen id="swNPArtAndDemNotNo">
      <whenValue element="np" attr="artAndDem" value="article"/>
      <or/>
      <whenValue element="np" attr="artAndDem" value="demonstrative"/>
      <or/>
      <whenValue element="np" attr="artAndDem" value="both"/>
   </showWhen>
   &TechnicalTerms; 
   
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/IPCompounds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="IPAux" count="2/2">
    <title level="2">Basic Sentences - Verb Compounds</title>
    <introduction>Verbs may combine with other verbs, or with nouns or other word categories to form verb compounds.  These compounds still act like verbs, though they may have changed their subcategorization, such as from a transitive verb to an intransitive verb. <br/><br/>
    Besides compounds which are written as a single word, there are also idiomatic expressions consisting of a verb and another word.  Examples of some of the most common types will be collected here, beginning with the true verb compounds.</introduction>
   <form section="ip">
<radioGroup>
   <groupName dataItem="heartCompound" default="no">RIPHeartCompound</groupName>
   <prompt><br/>Some languages have a set of verb compounds which all contain the noun which describes the center of emotions, such as the heart.  Does you language have this type of verb compound?</prompt>
   <radio id="IPHeartCompoundYes" dataValue="yes">Yes</radio>
   <radio id="IPHeartCompoundNo" dataValue="no">No</radio>
</radioGroup>     
      <prompt id="IPHeartCompoundExamplesPrompt" show="swIPHeartCompoundYes">Key examples of this special type of verb compound from your language here:</prompt>
      <textBox id="IPHeartCompoundExample" dataItem="heartCompoundExample" cols="50" show="swIPHeartCompoundYes"/>
        <br/>
        <br/>
      <radioGroup>
         <groupName dataItem="bodypartCompound" default="no">RIPBodypartCompound</groupName>
         <prompt><br/>Some languages have a set of verb compounds which consist of a verb and a bodypart noun<span id="IPHeartCompoundYesSpan" show="swIPHeartCompoundYes"> other than the one which describes the center of emotions for your language covered above</span>.  Does you language have this type of verb compound?</prompt>
         <radio id="IPBodypartCompoundYes" dataValue="yes">Yes</radio>
         <radio id="IPBodypartCompoundNo" dataValue="no">No</radio>
      </radioGroup>     
      <prompt id="IPBodypartCompoundExamplesPrompt" show="swIPBodypartCompoundYes">Key examples of this special type of verb compound from your language here:</prompt>
      <textBox id="IPBodypartCompoundExample" dataItem="bodypartCompoundExample" cols="50" show="swIPBodypartCompoundYes"/>
      <br/>
      <br/>
      <prompt id="IPVerbNCompoundExamplesPrompt">Key examples of <span id="IPHeartOrBodypartCompoundYesSpan" show="swIPHeartOrBodypartCompoundYes">any other </span>compounds consisting of a verb and a noun from your language here:</prompt>
      <textBox id="IPVerbNCompoundExample" dataItem="verbNCompoundExample" cols="50"/>
      <br/>
      <br/>
      <prompt id="IPVerbNCompoundSentExamplesPrompt">Now take some examples from <span id="IPHeartAndBodypartCompoundNoSpan" show="swIPHeartAndBodypartCompoundNo">the box</span><span id="IPHeartOrBodypartCompoundYesSpan2" show="swIPHeartOrBodypartCompoundYes">each box</span> above and use it in a full sentence here:</prompt>
      <textBox id="IPVerbNCompoundSentExample" dataItem="verbNCompoundSentExample" cols="50"/>
      <br/>
      <br/>
      <prompt id="IPVerbOtherCompoundExamplesPrompt">Key examples of compounds consisting of a verb and any other word category besides nouns from your language here:</prompt>
      <textBox id="IPVerbOtherCompoundExample" dataItem="verbOtherCompoundExample" cols="50"/>
      <br/>
      <br/>
      <prompt id="IPVerbOtherCompoundSentExamplesPrompt">Now take some examples from the box above and use it in a full sentence here:</prompt>
      <textBox id="IPVerbOtherCompoundSentExample" dataItem="verbOtherCompoundSentExample" cols="50"/>
      <br/>
      <br/>
      <prompt id="IPVerbIdiomExamplesPrompt">Next we want to consider the cases of a verb and another word or words that go together as a unit to express a notion that is not just the same as the combined meaning of the two independent words.  These are commonly called idioms.  Key examples of two or more word idioms from your language here:</prompt>
      <textBox id="IPVerbIdiomExample" dataItem="verbIdiomExample" cols="50"/>
      <instruction id="IPVerbIdiomInstruction">These multi-word idioms are best handled as a single verb entry in the lexicon using <tool>Join Compound</tool>.</instruction>
       <br/><br/>
        <buttons>
            <button id="IPCompoundsBack" value="Back" goto="IPAux.xml"/>
            <button id="IPCompoundsNext" value="Next" goto="IPContents.htm"/>
        </buttons>
   </form>
   <showWhen id="swIPHeartCompoundYes">
      <whenRadio button="IPHeartCompoundYes"/>
   </showWhen>
   <showWhen id="swIPBodypartCompoundYes">
      <whenRadio button="IPBodypartCompoundYes"/>
   </showWhen>
   <showWhen id="swIPHeartOrBodypartCompoundYes">
      <whenRadio button="IPHeartCompoundYes"/>
      <or/>
      <whenRadio button="IPBodypartCompoundYes"/>
   </showWhen>
   <showWhen id="swIPHeartAndBodypartCompoundNo">
      <whenRadio button="IPHeartCompoundNo"/>
      <and/>
      <whenRadio button="IPBodypartCompoundNo"/>
   </showWhen>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/es/XmlPageDescriptions/QPPartitive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd" [
<!ENTITY TechnicalTerms SYSTEM  "TechnicalTerms.xml">
]>
<?xml-stylesheet type="text/xsl" href="..\Transforms\PAWSSKHtmlMapper.xsl"?>
<page id="QPPartitive" count="5/7">
   <title level="2">Las frases cuantificadoras - Las construcciones partitivas</title>
   <introduction>Todos los cuantificadores, incluyendo números, normalmente pueden presentarse en construcciones <technicalTermRef term="ttPartitive">partitivas</technicalTermRef> que se usan para indicar que se está hablando de solo una parte de un grupo más grande. Algunos ejemplos son:
	</introduction>
   <EnglishExample>
      <exItem label="1.">algunos de los niños.</exItem>
      <exItem label="2.">varias de las niñas mayores.</exItem>
      <exItem label="3.">muchas de las mujeres.</exItem>
      <exItem label="4.">tanta del alimento.</exItem>
      <exItem label="5.">solamente diez de los chicos.</exItem>
   </EnglishExample>
   <introduction>Como se ve en los ejemplos, las construcciones partitivas usualmente se expresan con una <technicalTermRef term="ttAdpositionalPhrases">frase adposicional</technicalTermRef> que modifica al cuantificador y esta frase indica el grupo o la cosa en total de la que se habla.  Observe que en todos estos ejemplos, el sustantivo en la frase partitiva puede ser modificada aún más por una cláusula relativa. <br/> <br/>
      En algunas lenguas, es una cláusula relativa que indica el grupo en vez de una frase adposicional.
   </introduction>
	<form section="qp">
	   <prompt><br/>Escriba cómo su lengua expresa ejemplos similares de partitivos con cuantificadores aquí:</prompt>
	   <textBox id="QPPartitiveQExample" dataItem="partitiveQExample"/>
<br/><br/>
	   <radioGroup>
	      <groupName dataItem="partitive" default="no" >RQPPartitive</groupName>
	      <prompt>De acuerdo con los ejemplos, ¿utiliza su lengua frases adposicionales en las construcciones partitivas?</prompt>
	      <radio id="QPPartitiveYes" dataValue="yes">Sí</radio>
	      <radio id="QPPartitiveNo" dataValue="no">No, utiliza una cláusula relativa en su lugar</radio>
	      <radio id="QPPartitiveOther" dataValue="other">No, mi lengua utiliza otra manera que una frase adposicional o una cláusula relativa se utiliza para expresar significados similares</radio>
	   </radioGroup>
	   
	   <radioGroup id="QPPartitivePPPosTable" show="swQPPartitiveYes">
	      <groupName dataItem="partitivePPPos" default="unknown" position="yesHeadDiff">RQPPartitivePPPos</groupName>
	      <prompt>¿Dónde se presenta la frase adposicional con respecto al cuantificador?</prompt>
	      <radio id="QPPartitivePPBefore" checked="yes" dataValue="before">Antes</radio>
	      <radio id="QPPartitivePPAfter" checked="yes" dataValue="after">Después</radio>
	      <radio id="QPPartitivePPEitherSide" checked="yes" dataValue="either">De cualquier lado</radio>
	   </radioGroup>
	   
	   <prompt id="QPPartitiveOfPrompt" show="swQPPartitiveYes">Escriba las <technicalTermRef term="ttAdposition">adposiciones</technicalTermRef> que pueden utilizar para decir “de” en estas construcciones partitivas, con cada palabra en una línea separada. </prompt>
	   <textBox id="QPPartitiveOfExample" dataItem="partitiveOf" rows="3" show="swQPPartitiveYes"/>
	   <br/>
	   
	   <prompt id="QPPartitiveRelClPrompt" show="swQPPartitiveNo">La estructura de las cláusulas relativas se presenta en <section number="12">Las cláusulas relativas</section>.</prompt>
<br/>		<br/>
		<buttons>
			<button id="QPPartitiveBack" value="Back" goto="QPCardinal.xml"/>
		    <button id="QPPartitiveNext" value="Next" goto="QPCatMap.xml" gotoNoGrammar="Contents.htm"/>
		</buttons>
	</form>
   <showWhen id="swQPPartitiveNo">
      <whenRadio button="QPPartitiveNo"/>  
   </showWhen> 
   <showWhen id="swQPPartitiveYes">
      <whenRadio button="QPPartitiveYes"/>  
   </showWhen> 
   &TechnicalTerms; 
   
</page>

=== sillsdev/CarlaLegacy/PAWS/XMLPageDescriptions/QCatMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="QCatMap">
	<title level="2">Questions - Category Mapper</title>
	<form section="q">
		<instruction>You need to make sure the interrogative words which act as pronouns in your lexicon will be mapped to the syntactic category <category>Pron</category>.  Choose one of the following options, depending on your situation (be sure that you have also entered the feature <feature>wh</feature> on each entry as directed earlier):
<ul>
				<li>If you already have these interrogative pronouns marked with the category <category>Pron</category> in your lexicon, nothing more needs to be done.</li>
				<li>If the interrogative pronouns are mixed in with another category in the lexicon, you either need to give them the category <category>Pron</category> in your morphological parser, or add the feature <feature>makePron</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.</li>
				<li>If you have the interrogative pronouns marked in your lexicon with a distinct category all their own, even if it includes the other interrogative words since they were mapped individually to their appropriate syntactic category, enter that category below so PAWS can map your morphological category to <category>Pron</category>. <br/>
					<catMap id="QWhPronCategory" dataItem="whPronCategory">Pron</catMap>
				</li>
			</ul>

</instruction>
			<br/>
				<br/>
		<buttons>
			<button id="QCatMapBack" value="Back" goto="QEmbCont.htm"/>
			<button id="QCatMapNext" value="Next" goto="QTesting.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/CoordTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="CoordTesting" count="3/3">
	<title level="2">Cooordination Constructions - Testing</title>
	<form section="coord">
		<instruction>To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
	<br/>
	<br/>
Run the file <file id="CoordTestingFile" section="coord">xxxCoordTest.txt</file> through your morphological parser and then
run the syntactic parser on the output (all possible within CarlaStudio, as noted on the 'Contents' page).  Check the log for the
results and note any changes you need to make, most likely by adding features to particular entries in the lexicon.  If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, so you need to fix the problem with the morphlogical parser first.  You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.   Or you may need to use the Category Mapper on the previous page to correct differences between your categories and those used by PAWS.  Make the changes as needed.  If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  Rerun the parsers and check the results again.
			<br/>
			<br/>
Please check off this section now in 'Contents' and then proceed to
<section number="17">Focus and Topic Constructions</section> when you are ready.
</instruction>
<br/>
		<br/>
		<buttons>
			<button id="CoordTestingBack" value="Back" goto="CoordCatMap.xml"/>
			<button id="CoordTestingNext" value="Next" goto="Contents.htm"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/XmlPageDescriptions/AdvPCatMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="AdvPCatMap" count="6/7">
	<title level="2">Adverbs and Adverb Phrases - Category Mapper</title>
	<form section="advp">
		<instruction>You need to make sure the adverbs in your lexicon will be mapped to the syntactic category <category>Adv</category>.  Choose one of the following options, depending on your situation:
<ul>
				<li>If you already have adverbs marked with the category <category>Adv</category> in your lexicon, nothing
  more needs to be done.</li>
				<li>If adverbs are mixed in with another category in the lexicon, you either need to give them the category <category>Adv</category> in your morphological parser, or add the feature <feature>makeAdv</feature> to each appropriate entry in the lexicon so the category will be changed for the syntax.  (If a particular entry can also be used as another syntactic category, make a separate lexical entry for each use.)</li>
				<li>If you have adverbs marked in your lexicon with a distinct category all their own, but it is different from <category>Adv</category>, enter that category below so PAWS can map your morphological category to <category>Adv</category>. <br/>
					<catMap id="AdvPAdverbCategory" dataItem="adverbCategory">Adv</catMap>
				</li>
			</ul>
		</instruction>
		<br/>
		<buttons>
			<button id="AdvPCatMapBack" value="Back" goto="AdvPDegree.xml"/>
			<button id="AdvPCatMapNext" value="Next" goto="AdvPTesting.xml"/>
		</buttons>
	</form>
</page>

=== sillsdev/CarlaLegacy/Cabhab/Configurations/PAWS/Localizations/en/XmlPageDescriptions/IPTesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Andy Black (SIL International) -->
<!DOCTYPE page SYSTEM "..\Data\PAWSSKHtmlMapper.dtd">
<?xml-stylesheet type="text/xsl" href="..\Templates\PAWSSKHtmlMapper.xsl"?>
<page id="IPTesting" count="1/1">
	<title level="2">Basic, Single-Clause Sentences - Testing</title>
	<form section="ip">
	<instruction>To test what you have done so far, save your work now.  This will generate the test file and grammar rules file created to this point.
<br/>
	<br/>
Run the file <file id="IPTestingFile" section="ip">xxxIPTest.txt</file> through your morphological parser and then
run the syntactic parser on the output (all possible within CarlaStudio, as noted on the ‘Contents’ page).  Check the log for the
results and note any changes you need to make, most likely by adding features to particular entries in the lexicon.  If any words fail to be parsed by your morphological parser, then the syntactic parser cannot parse any phrases or sentences those words are included in, so you need to fix the problem with the morphlogical parser first.  You may also find you need to change your answers on the previous pages of PAWS about the order of elements in the phrase structure rules.   Or you may need to use the Category Mapper on the previous page to correct differences between your categories and those used by PAWS.  Make the changes as needed.  If you have changed anything on the pages within PAWS, you will need to return to this page and then save the files again.  Rerun the parsers and check the results again.<br/>
			<br/>
(Note: any examples with nonfinite auxiliaries in embedded clauses will not be able to be tested until you complete <section number="10">Complement Clauses</section> so they will appear in <file id="CompTestingFile" section="comp">xxxCompTest.txt</file> instead of this file.)
<br/>
<br/>
Please check off this section now in ‘Contents’ and then proceed to
<section number="10">Complement Clauses</section> when you are ready.
		</instruction>
<br/>
		<br/>
		<buttons>
			<button id="IPTestingBack" value="Back" goto="IPContents.htm"/>
			<button id="IPTestingNext" value="Next" goto="IPContents.htm"/>
		</buttons>
	</form>
</page>
